--------  Paste GVCGenericObjects.eomodeld SQL starting here ---------------------------------------
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

CREATE TABLE "GVC_LOOKUP" (
	"name" VARCHAR(50) NOT NULL,
	"the_id" BYTE(24) NOT NULL
);

CREATE TABLE "GVC_VA_OBJECT" (
	"is_active" CHARACTER(1) NOT NULL,
	"the_id" BYTE(24) NOT NULL
);

SET UNIQUE = 1000000 FOR "GVC_LOOKUP";

SET UNIQUE = 1000000 FOR "GVC_VA_OBJECT";

ALTER TABLE "GVC_LOOKUP" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GVC_VA_OBJECT" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

COMMIT;
--------  Paste GVCGenericObjects.eomodeld SQL ending here ----------------------------------------

--------  Paste GVCVirtualTables.eomodeld SQL starting here ---------------------------------------
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

CREATE TABLE "VIRTUAL_COLUMN" (
	"COLUMN_ID" BYTE(24) CONSTRAINT NOT_NULL_VIRTUAL_COLUMN__COLUMN_ID NOT NULL,
	"COLUMN_TYPE_ID" BYTE(24) CONSTRAINT NOT_NULL_VIRTUAL_COLUMN__COLUMN_TYPE_ID NOT NULL,
	"DATE_CREATED" TIMESTAMP WITH TIME ZONE CONSTRAINT NOT_NULL_VIRTUAL_COLUMN__DATE_CREATED NOT NULL,
	"EXPRESSION" VARCHAR(2000000),
	"IS_SYSTEM_COLUMN" CHARACTER(1) CONSTRAINT NOT_NULL_VIRTUAL_COLUMN__IS_SYSTEM_COLUMN NOT NULL,
	"NAME" VARCHAR(100) CONSTRAINT NOT_NULL_VIRTUAL_COLUMN__NAME NOT NULL,
	"RESTRICTING_VALUE" VARCHAR(50) CONSTRAINT NOT_NULL_VIRTUAL_COLUMN__RESTRICTING_VALUE NOT NULL,
	"TABLE_ID" BYTE(24) CONSTRAINT NOT_NULL_VIRTUAL_COLUMN__TABLE_ID NOT NULL,
	"TEXT_DESCRIPTION" VARCHAR(1999),
	"LOOKUP_COLUMN_ID" BYTE(24)
);

CREATE TABLE "COLUMN_TYPE" (
	"ENTITY_NAME_RESTRICTOR" VARCHAR(50) NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"TEXT_DESCRIPTION" VARCHAR(1999),
	"the_id" BYTE(24) NOT NULL
);

CREATE TABLE "ROOT_TABLE" (
	"DATE_CREATED" TIMESTAMP WITH TIME ZONE NOT NULL,
	"DATE_MODIFIED" TIMESTAMP WITH TIME ZONE NOT NULL,
	"NAME" VARCHAR(100) NOT NULL,
	"TABLE_ID" BYTE(24) NOT NULL,
	"TEXT_DESCRIPTION" VARCHAR(1999)
);

CREATE TABLE "VIRTUAL_FIELD" (
	"RESTRICTING_VALUE" VARCHAR(50) NOT NULL,
      "BOOLEAN_VALUE" VARCHAR(5),
	"VIRTUAL_COLUMN_ID" BYTE(24) NOT NULL,
	"VIRTUAL_FIELD_ID" BYTE(24) NOT NULL,
	"VIRTUAL_ROW_ID" BYTE(24) NOT NULL,
	"LOOKUP_VALUE_ID" BYTE(24),
	"LONG_STRING_VALUE" CLOB,
	"NUMBER_VALUE" DECIMAL(30,10),
	"STRING_VALUE" VARCHAR(6000000),
	"TIMESTAMP_VALUE" TIMESTAMP
);

CREATE TABLE "VIRTUAL_ROW" (
	"VIRTUAL_ROW_ID" BYTE(24) NOT NULL,
	"VIRTUAL_TABLE_ID" BYTE(24) NOT NULL
);

CREATE TABLE "VIRTUAL_TABLE" (
	"DATE_CREATED" TIMESTAMP NOT NULL,
	"DATE_MODIFIED" TIMESTAMP NOT NULL,
	"NAME" VARCHAR(300) NOT NULL,
	"TABLE_ID" BYTE(24) NOT NULL,
	"TEXT_DESCRIPTION" VARCHAR(6000)
);

SET UNIQUE = 1000000 FOR "VIRTUAL_COLUMN";

SET UNIQUE = 1000000 FOR "VIRTUAL_COLUMN";

SET UNIQUE = 1000000 FOR "VIRTUAL_COLUMN";

SET UNIQUE = 1000000 FOR "COLUMN_TYPE";

SET UNIQUE = 1000000 FOR "VIRTUAL_TABLE";

SET UNIQUE = 1000000 FOR "ROOT_TABLE";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_ROW";

ALTER TABLE "VIRTUAL_COLUMN" ADD CONSTRAINT PRIMARY_KEY_VIRTUAL_COLUMN_COLUMN_ID PRIMARY KEY ("COLUMN_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "COLUMN_TYPE" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ROOT_TABLE" ADD PRIMARY KEY ("TABLE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "VIRTUAL_FIELD" ADD PRIMARY KEY ("VIRTUAL_FIELD_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "VIRTUAL_ROW" ADD PRIMARY KEY ("VIRTUAL_ROW_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "VIRTUAL_TABLE" ADD PRIMARY KEY ("TABLE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "VIRTUAL_COLUMN" ADD CONSTRAINT FOREIGN_KEY_VIRTUAL_COLUMN_COLUMN_TYPE_ID_COLUMN_TYPE_the_id FOREIGN KEY ("COLUMN_TYPE_ID") REFERENCES "COLUMN_TYPE" ("THE_ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "VIRTUAL_FIELD" ADD FOREIGN KEY ("VIRTUAL_ROW_ID") REFERENCES "VIRTUAL_ROW" ("VIRTUAL_ROW_ID") DEFERRABLE INITIALLY DEFERRED;

COMMIT;

--------  Paste GVCVirtualTables.eomodeld SQL ending here -----------------------------------------

--------  Paste GVCSiteMaker.eomodeld SQL starting here -------------------------------------------
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

CREATE TABLE "SM_BANNER" (
	"BANNER_TEXT" VARCHAR(300),
	"WEBSITE_FKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_CHANGE_LOG" (
	"CHANGES" VARCHAR(1999),
	"DATE_RECORDED" TIMESTAMP WITH TIME ZONE NOT NULL,
	"NOTES" VARCHAR(1999),
	"OID" BYTE(24) NOT NULL,
	"USER_FKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_ERROR_LOG" (
	"APP_NAME" VARCHAR(100),
	"COMPONENT_NAME" VARCHAR(100),
	"EVENT_DATE" TIMESTAMP WITH TIME ZONE,
	"EXCEPTION_MESSAGE" VARCHAR(1999),
	"HOST_NAME" VARCHAR(100),
	"LOG_TYPE" VARCHAR(100),
	"OID" BYTE(24) NOT NULL,
	"PAGE_NAME" VARCHAR(100),
	"REQUEST" CLOB,
	"STACK_TRACE" CLOB,
	"USER_ID" VARCHAR(100)
);

CREATE TABLE "SM_FILE_PASSWORD" (
	"EXPIRATION_DATE" TIMESTAMP WITH TIME ZONE,
	"FILE_PASSWORD_PKEY" BYTE(24) NOT NULL,
	"PASSWORD" VARCHAR(50),
	"SITE_FILE_PASSWORD_FKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_FOOTER" (
	"LINK_TEXT_1" VARCHAR(300),
	"LINK_TEXT_2" VARCHAR(300),
	"LINK_TEXT_3" VARCHAR(300),
	"LINK_TEXT_4" VARCHAR(300),
	"LINK_URL_1" VARCHAR(255),
	"LINK_URL_2" VARCHAR(255),
	"LINK_URL_3" VARCHAR(255),
	"LINK_URL_4" VARCHAR(255),
	"WEBSITE_FKEY" BYTE(24) NOT NULL,
	"CUSTOM_FOOTER" CLOB
);

CREATE TABLE "SM_GROUP" (
	"CREATION_DATE" TIMESTAMP WITH TIME ZONE,
	"GROUP_PKEY" BYTE(24) NOT NULL,
	"GROUP_NAME" VARCHAR(150) NOT NULL,
	"LDAP_GROUP_NAME" VARCHAR(255),
	"OID_LDAP_BRANCH" BYTE(24),
	"TYPE" VARCHAR(25) NOT NULL,
	"PARENT_WEBSITE" BYTE(24),
	"SECRET" VARCHAR(255),
	"OID_SECTION_STYLE" BYTE(24)
);

CREATE TABLE "SM_GROUP_FILE" (
	"FILE_PKEY" BYTE(24) NOT NULL,
	"GROUP_PKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_GROUP_SECTION" (
	"GROUP_PKEY" BYTE(24) NOT NULL,
	"SECTION_PKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_LDAP_BRANCH" (
	"DISPLAY_NAME" VARCHAR(100) NOT NULL,
	"DISPLAY_ORDER" INTEGER NOT NULL,
	"GROUP_SUBTREE" VARCHAR(100) NOT NULL,
	"INSTRUCTIONS" VARCHAR(1999),
	"LDAP_ENTITY_NAME" VARCHAR(50) NOT NULL,
	"OID" BYTE(24),
	"USER_ID_ATTR" VARCHAR(50) NOT NULL,
	"USER_SUBTREE" VARCHAR(100) NOT NULL
);

CREATE TABLE "SM_ORG_UNIT" (
	"WEBSITE_CREATION_MESSAGE" CLOB,
	"DEPTH" NUMERIC,
	"FILE_SIZE_QUOTA" NUMERIC,
	"FILE_SIZE_USAGE" NUMERIC,
	"IN_PUBLIC_LIST" CHAR(1) NOT NULL,
	"OID" BYTE(24) NOT NULL,
	"OID_PARENT_ORG_UNIT" BYTE(24),
	"UNIT_NAME" VARCHAR(765)
);

CREATE TABLE "SM_ORG_UNIT_USER" (
	"ORG_UNIT_OID" BYTE(24) NOT NULL,
	"USER_PKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_VIRTUAL_TABLE" (
	"CREATE_USER_FKEY" BYTE(24) NOT NULL,
	"DATE_CREATED" TIMESTAMP WITH TIME ZONE NOT NULL,
	"DATE_MODIFIED" TIMESTAMP WITH TIME ZONE NOT NULL,
	"NAME" VARCHAR(300) NOT NULL,
	"TABLE_ID" BYTE(24) NOT NULL,
	"TEXT_DESCRIPTION" VARCHAR(6000),
	"UPDATE_USER_FKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_SECTION" (
	"COMPONENT_ID" BYTE(24) NOT NULL,
	"DETAILS" VARCHAR(255),
	"INDENTATION" NUMERIC NOT NULL,
	"IS_NAVIGABLE" CHARACTER(1) NOT NULL,
	"REQUIRE_HTTPS_ACCESS" CHARACTER(1) NOT NULL,
	"IS_AUTO_VERSIONING" CHARACTER(1) NOT NULL,
	"IS_VERSIONING" CHARACTER(1) NOT NULL,
	"MIME_TYPE" VARCHAR(50) NOT NULL,
	"NAME" VARCHAR(255) NOT NULL,
	"NORMAL_NAME" VARCHAR(255) NOT NULL,
	"OID_SECTION_STYLE" BYTE(24),
	"SECTION_ORDER" NUMERIC NOT NULL,
	"SECTION_PKEY" BYTE(24) NOT NULL,
	"TYPE_OID" BYTE(24) NOT NULL,
	"WEBSITE_FKEY" BYTE(24) NOT NULL
);
CREATE TABLE "SM_SECTION_CONTRIBUTOR_GROUP" (
	"GROUP_PKEY" BYTE(24) NOT NULL,
	"SECTION_PKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_SECTION_EDITOR_GROUP" (
	"GROUP_PKEY" BYTE(24) NOT NULL,
	"SECTION_PKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_SECTION_STYLE" (
	"BANNER_COMP" VARCHAR(50) NOT NULL,
	"DATE_CREATED" TIMESTAMP WITH TIME ZONE NOT NULL,
	"DATE_MODIFIED" TIMESTAMP WITH TIME ZONE,
	"DEFAULT_STYLE" CHAR(1) NOT NULL,
	"FOOTER_COMP" VARCHAR(50) NOT NULL,
	"NAME" VARCHAR(300),
	"NAVBAR_COMP" VARCHAR(50) NOT NULL,
	"NOTES" VARCHAR(6000),
	"OID" BYTE(24) NOT NULL,
	"OID_CREATED_BY" BYTE(24) NOT NULL,
	"OID_MODIFIED_BY" BYTE(24),
	"OID_OWN_UNIT" BYTE(24) NOT NULL,
	"PAGE_SCFLD_COMP" VARCHAR(50) NOT NULL,
	"PUBLISHED" CHAR(1) NOT NULL,
	"RELATED_CSS_URL" VARCHAR(100),
	"RESOURCE_DIR" VARCHAR(100),
	"SECT_CONT_COMP" VARCHAR(50) NOT NULL,
	"STYLE_ID" VARCHAR(50),
	"TEMPLATE" CLOB
);

CREATE TABLE "SM_SECTION_TYPE" (
	"EDITOR_NAME" VARCHAR(100) NOT NULL,
	"key" VARCHAR(50) NOT NULL,
	"NAME" VARCHAR(100) NOT NULL,
	"OID" BYTE(24) NOT NULL,
	"ORDER" NUMERIC NOT NULL,
	"PAGE_COMP_ENTITY" VARCHAR(100) NOT NULL
);

CREATE TABLE "SM_SECTION_VERSION" (
	"CREATED_DATE" TIMESTAMP,
	"DETAILS" VARCHAR(255),
	"IS_LOCKED" CHARACTER(1) NOT NULL,
	"MODIFIED_DATE" TIMESTAMP,
	"NAME" VARCHAR(50) NOT NULL,
	"OID_COMPONENT" BYTE(24) NOT NULL,
	"OID_CREATED_BY" BYTE(24) NOT NULL,
	"OID_MODIFIED_BY" BYTE(24),
	"OID_SECTION" BYTE(24) NOT NULL,
	"VERSION_NUMBER" NUMERIC NOT NULL,
	"VERSION_PKEY" BYTE(24) NOT NULL,
	"COMPONENT_ORDER" INTEGER
);

CREATE TABLE "SM_SITE_FILE" (
	"FILE_DESCRIPTION" VARCHAR(6000),
	"FILE_PKEY" BYTE(24) NOT NULL,
	"FILE_SIZE_USAGE" NUMERIC,
	"FILENAME" VARCHAR(300),
	"MIME_TYPE" VARCHAR(50),
	"OID_SITE_FILE_FOLDER" BYTE(24) NOT NULL,
	"SHORT_NAME" VARCHAR(100),
	"UPLOAD_DATE" TIMESTAMP WITH TIME ZONE,
	"UPLOADED_FILENAME" VARCHAR(300),
	"WEBSITE_FKEY" BYTE(24)
);

CREATE TABLE "SM_SITE_FILE_FOLDER" (
	"NAME" VARCHAR(765) NOT NULL,
	"OID" BYTE(24) NOT NULL,
	"OID_PARENT_FOLDER" BYTE(24),
	"WEBSITE_FKEY" BYTE(24) 
);

CREATE TABLE "SM_STYLE" (
	"DATE_CREATED" TIMESTAMP WITH TIME ZONE NOT NULL,
	"DATE_MODIFIED" TIMESTAMP WITH TIME ZONE,
	"NAME" VARCHAR(300) NOT NULL,
	"NOTES" VARCHAR(6000),
	"OID" BYTE(24) NOT NULL,
	"OID_CREATED_BY" BYTE(24) NOT NULL,
	"OID_MODIFIED_BY" BYTE(24),
	"OID_OWN_UNIT" BYTE(24) NOT NULL,
	"PUBLISHED" CHAR(1) NOT NULL,
	"STYLE_ID" VARCHAR(150) NOT NULL,
	"TEMPLATE" CLOB
);

CREATE TABLE "TASK_SECTION" (
	"SECTION_ID" BYTE(24) NOT NULL,
	"TASK_ID" BYTE(24) NOT NULL
);

CREATE TABLE "TASK_STATUS" (
	"key" VARCHAR(50) NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"the_id" BYTE(24) NOT NULL
);

CREATE TABLE "TASK_TABLE" (
	"TASK_ID" BYTE(24) NOT NULL,
	"TABLE_ID" BYTE(24) NOT NULL
);

CREATE TABLE "SM_USAGE_LOG" (
	"ACCESS_TIME" TIMESTAMP WITH TIME ZONE,
	"USAGE_LOG_PKEY" BYTE(24) NOT NULL,
	"USER_PKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_USER" (
	"ORG_UNIT_FOR_STYLES" BYTE(24),
	"PASSWORD" VARCHAR(300),
	"USER_ID" VARCHAR(300) NOT NULL,
	"USER_PKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_USER_GROUP" (
	"GROUP_PKEY" BYTE(24) NOT NULL,
	"USER_PKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_WEBSITE" (
	"CAN_REPLICATE" CHAR(1),
	"CONTACT_EMAIL" VARCHAR(300),
	"CONTACT_FAX" VARCHAR(75),
	"CONTACT_NAME" VARCHAR(300),
	"CONTACT_PHONE" VARCHAR(75),
	"DATE_LAST_MODIFIED" TIMESTAMP,
	"DATE_CREATED" TIMESTAMP,
	"FILE_SIZE_USAGE" NUMERIC,
	"GROUP_PKEY" BYTE(24),
	"MEG_QUOTA" NUMERIC,
	"OID_PARENT_ORG_UNIT" BYTE(24),
	"OID_SECTION_STYLE" BYTE(24) NOT NULL,
	"PUBLICATION_PERMITTED" CHAR(1),
	"PUBLISHED" CHAR(1),
	"REDIRECT_URL" VARCHAR(255),
	"SHOW_BANNER" CHAR(1),
	"SHOW_FOOTER" CHAR(1),
	"SHOW_LOGIN_LOGOUT_LINKS" CHAR(1),
	"SHOW_NAVBAR" CHAR(1),
	"SITE_ID" VARCHAR(150),
	"CUSTOM_HEADER_CONTENT" CLOB,
	"USER_FKEY" BYTE(24),
	"WEBSITE_PKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_WEBSITE_CHANGE_LOG" (
	"CHANGES" VARCHAR(1999),
	"DATE_RECORDED" TIMESTAMP WITH TIME ZONE NOT NULL,
	"NOTES" VARCHAR(1999),
	"OID" BYTE(24) NOT NULL,
	"USER_FKEY" BYTE(24) NOT NULL,
	"WEBSITE_FKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_WEBSITE_REQUEST" (
	"ADMINISTRATIVE_NOTES" CLOB,
	"DATE_REQUESTED" TIMESTAMP WITH TIME ZONE NOT NULL,
	"DATE_RESOLVED" TIMESTAMP WITH TIME ZONE,
	"OID" BYTE(24) NOT NULL,
	"ORG_UNIT_OID" BYTE(24) NOT NULL,
	"REQUESTOR_NOTE" VARCHAR(1999),
	"SITE_ID" VARCHAR(50) NOT NULL,
	"USER_FKEY" BYTE(24) NOT NULL,
	"WEBSITE_FKEY" BYTE(24)
);

CREATE TABLE "SM_WEBSITE_TABLE" (
	"TABLE_ID" BYTE(24) NOT NULL,
	"WEBSITE_FKEY" BYTE(24) NOT NULL
);

CREATE TABLE "SM_DA_WEBSITE_GRP_NOTIFICATION" (
	"GROUP_PKEY" BYTE(24) NOT NULL,
	"COMPONENT_ID" BYTE(24) NOT NULL
);

CREATE TABLE "TASK" (
	"BINDINGS" CLOB,
	"CREATED_DATE" TIMESTAMP WITH TIME ZONE NOT NULL,
	"DETAILS" VARCHAR(255),
	"FAILURE_REASON" VARCHAR(1999),
	"IS_NAVIGABLE" CHARACTER(1),
	"RELATED_SECTION_ID" BYTE(24),
	"SOURCE_SECTION_ID" BYTE(24),
	"STATUS_ID" BYTE(24) NOT NULL,
	"TASK_ID" BYTE(24) NOT NULL,
	"TASK_TYPE" VARCHAR(255) NOT NULL,
	"USER_ID" BYTE(24) NOT NULL,
	"ORG_UNIT_ID" BYTE(24),
	"REQUEST_ID" BYTE(24),
	"RELATED_SITE_FILE_FOLDER_ID" BYTE(24),
	"RELATED_TABLE_ID" BYTE(24),
	"RELATED_SITE_FILE_ID" BYTE(24)
);

SET UNIQUE = 1000000 FOR "SM_BANNER";

SET UNIQUE = 1000000 FOR "SM_CHANGE_LOG";

SET UNIQUE = 1000000 FOR "SM_SECTION_TYPE";

SET UNIQUE = 1000000 FOR "SM_SECTION_TYPE";

SET UNIQUE = 1000000 FOR "SM_SECTION_TYPE";

SET UNIQUE = 1000000 FOR "SM_SECTION_TYPE";

SET UNIQUE = 1000000 FOR "SM_SECTION_TYPE";

SET UNIQUE = 1000000 FOR "SM_SECTION_TYPE";

SET UNIQUE = 1000000 FOR "SM_ERROR_LOG";

SET UNIQUE = 1000000 FOR "SM_FILE_PASSWORD";

SET UNIQUE = 1000000 FOR "SM_FOOTER";

SET UNIQUE = 1000000 FOR "SM_GROUP";

SET UNIQUE = 1000000 FOR "SM_LDAP_BRANCH";

SET UNIQUE = 1000000 FOR "SM_ORG_UNIT";

SET UNIQUE = 1000000 FOR "SM_VIRTUAL_TABLE";

SET UNIQUE = 1000000 FOR "SM_SECTION";

SET UNIQUE = 1000000 FOR "SM_STYLE";

SET UNIQUE = 1000000 FOR "SM_SECTION_STYLE";

SET UNIQUE = 1000000 FOR "SM_SECTION_VERSION";

SET UNIQUE = 1000000 FOR "SM_SITE_FILE";

SET UNIQUE = 1000000 FOR "SM_SITE_FILE_FOLDER";

SET UNIQUE = 1000000 FOR "TASK_STATUS";

SET UNIQUE = 1000000 FOR "SM_USAGE_LOG";

SET UNIQUE = 1000000 FOR "SM_USER";

SET UNIQUE = 1000000 FOR "SM_WEBSITE";

SET UNIQUE = 1000000 FOR "SM_WEBSITE_CHANGE_LOG";

SET UNIQUE = 1000000 FOR "SM_WEBSITE_REQUEST";

SET UNIQUE = 1000000 FOR "SM_DA_WEBSITE_GRP_NOTIFICATION";

SET UNIQUE = 1000000 FOR "TASK";

ALTER TABLE "SM_BANNER" ADD PRIMARY KEY ("WEBSITE_FKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_CHANGE_LOG" ADD PRIMARY KEY ("OID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_DA_WEBSITE_GRP_NOTIFICATION" ADD PRIMARY KEY ("GROUP_PKEY","COMPONENT_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_ERROR_LOG" ADD PRIMARY KEY ("OID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_FILE_PASSWORD" ADD PRIMARY KEY ("FILE_PASSWORD_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_FOOTER" ADD PRIMARY KEY ("WEBSITE_FKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_GROUP" ADD PRIMARY KEY ("GROUP_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TASK" ADD PRIMARY KEY ("TASK_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_GROUP_FILE" ADD PRIMARY KEY ("GROUP_PKEY","FILE_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_GROUP_SECTION" ADD PRIMARY KEY ("GROUP_PKEY","SECTION_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_ORG_UNIT" ADD PRIMARY KEY ("OID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_ORG_UNIT_USER" ADD PRIMARY KEY ("ORG_UNIT_OID","USER_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_VIRTUAL_TABLE" ADD PRIMARY KEY ("TABLE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_SECTION" ADD PRIMARY KEY ("SECTION_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_SECTION_CONTRIBUTOR_GROUP" ADD PRIMARY KEY ("GROUP_PKEY","SECTION_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_SECTION_EDITOR_GROUP" ADD PRIMARY KEY ("GROUP_PKEY","SECTION_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_SECTION_STYLE" ADD PRIMARY KEY ("OID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_SECTION_TYPE" ADD PRIMARY KEY ("OID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_SECTION_VERSION" ADD PRIMARY KEY ("VERSION_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_SITE_FILE" ADD PRIMARY KEY ("FILE_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_SITE_FILE_FOLDER" ADD PRIMARY KEY ("OID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_STYLE" ADD PRIMARY KEY ("OID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TASK_STATUS" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TASK_SECTION" ADD PRIMARY KEY ("TASK_ID","SECTION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_USAGE_LOG" ADD PRIMARY KEY ("USAGE_LOG_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_USER" ADD PRIMARY KEY ("USER_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TASK_TABLE" ADD PRIMARY KEY ("TABLE_ID","TASK_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_USER_GROUP" ADD PRIMARY KEY ("GROUP_PKEY","USER_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_WEBSITE" ADD PRIMARY KEY ("WEBSITE_PKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_WEBSITE_CHANGE_LOG" ADD PRIMARY KEY ("OID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_WEBSITE_TABLE" ADD PRIMARY KEY ("TABLE_ID","WEBSITE_FKEY") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_WEBSITE_REQUEST" ADD PRIMARY KEY ("OID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_CHANGE_LOG" ADD FOREIGN KEY ("USER_FKEY") REFERENCES "SM_USER" ("USER_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "SM_ORG_UNIT_USER" ADD FOREIGN KEY ("USER_PKEY") REFERENCES "SM_USER" ("USER_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "SM_ORG_UNIT_USER" ADD FOREIGN KEY ("ORG_UNIT_OID") REFERENCES "SM_ORG_UNIT" ("OID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "SM_WEBSITE_CHANGE_LOG" ADD FOREIGN KEY ("WEBSITE_FKEY") REFERENCES "SM_WEBSITE" ("WEBSITE_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "SM_WEBSITE_CHANGE_LOG" ADD FOREIGN KEY ("USER_FKEY") REFERENCES "SM_USER" ("USER_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "SM_WEBSITE_REQUEST" ADD FOREIGN KEY ("WEBSITE_FKEY") REFERENCES "SM_WEBSITE" ("WEBSITE_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "SM_WEBSITE_REQUEST" ADD FOREIGN KEY ("USER_FKEY") REFERENCES "SM_USER" ("USER_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "SM_WEBSITE_REQUEST" ADD FOREIGN KEY ("ORG_UNIT_OID") REFERENCES "SM_ORG_UNIT" ("OID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TASK" ADD FOREIGN KEY ("STATUS_ID") REFERENCES "TASK_STATUS" ("THE_ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TASK" ADD FOREIGN KEY ("SOURCE_SECTION_ID") REFERENCES "SM_SECTION" ("SECTION_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TASK" ADD FOREIGN KEY ("RELATED_SECTION_ID") REFERENCES "SM_SECTION" ("SECTION_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TASK" ADD FOREIGN KEY ("ORG_UNIT_ID") REFERENCES "SM_ORG_UNIT" ("OID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TASK" ADD FOREIGN KEY ("RELATED_SITE_FILE_FOLDER_ID") REFERENCES "SM_SITE_FILE_FOLDER" ("OID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TASK" ADD FOREIGN KEY ("RELATED_SITE_FILE_ID") REFERENCES "SM_SITE_FILE" ("FILE_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "SM_SECTION_CONTRIBUTOR_GROUP" ADD FOREIGN KEY ("SECTION_PKEY") REFERENCES "SM_SECTION" ("SECTION_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "SM_SECTION_EDITOR_GROUP" ADD FOREIGN KEY ("SECTION_PKEY") REFERENCES "SM_SECTION" ("SECTION_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "SM_SECTION_VERSION" ADD FOREIGN KEY ("OID_SECTION") REFERENCES "SM_SECTION" ("SECTION_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TASK_SECTION" ADD FOREIGN KEY ("SECTION_ID") REFERENCES "SM_SECTION" ("SECTION_PKEY") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TASK_TABLE" ADD FOREIGN KEY ("TABLE_ID") REFERENCES "SM_VIRTUAL_TABLE" ("TABLE_ID") DEFERRABLE INITIALLY DEFERRED;


COMMIT;
--------  Paste GVCSiteMaker.eomodeld SQL ending here ---------------------------------------

--------  Paste PageComponents.eomodeld SQL starting here -------------------------------------------
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

CREATE TABLE "SM_PAGE_COMP" (
	"BINDINGS" CLOB,
	"COMPONENT_ID" BYTE(24) NOT NULL,
	"COMPONENT_TYPE" VARCHAR(255) NOT NULL,
	"DATE_MODIFIED" TIMESTAMP WITH TIME ZONE,
	"EMBED_SECTION_FKEY" BYTE(24),
	"EMBED_WEBSITE_FKEY" BYTE(24),
	"FIELD_ID" BYTE(24),
	"PARENT_ID" BYTE(24),
	"RELATED_FILE_ID" BYTE(24),
	"RELATED_SECTION_ID" BYTE(24),
	"SUB_TYPE" VARCHAR(50),
	"TABLE_ID" BYTE(24),
	"COLUMN_ID" BYTE(24),
	"TEMPLATE_OID" BYTE(24)
);

CREATE TABLE "SM_DA_MODE_TEMPLATE" (
	"HTML" CLOB,
	"OID" BYTE(24) NOT NULL
);


CREATE TABLE "SM_DA_COLUMN_NOTIFICATION" (
	"COMPONENT_ID" BYTE(24) NOT NULL,
	"COLUMN_COMPONENT_ID" BYTE(24) NOT NULL
);

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_PAGE_COMP";

SET UNIQUE = 1000000 FOR "SM_DA_MODE_TEMPLATE";

SET UNIQUE = 1000000 FOR "SM_DA_COLUMN_NOTIFICATION";

ALTER TABLE "SM_PAGE_COMP" ADD PRIMARY KEY ("COMPONENT_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_DA_MODE_TEMPLATE" ADD PRIMARY KEY ("OID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SM_DA_COLUMN_NOTIFICATION" ADD PRIMARY KEY ("COMPONENT_ID","COLUMN_COMPONENT_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;


COMMIT;
--------  Paste PageComponents.eomodeld SQL Ending here ---------------------------------------------


--
-- Changes to the generated SQL for GVC.SiteMaker purposes
--
SET UNIQUE = 1 FOR "GVC_LOOKUP";
SET UNIQUE = 1 FOR "GVC_VA_OBJECT";
SET UNIQUE = 1 FOR "VIRTUAL_COLUMN";
SET UNIQUE = 1 FOR "COLUMN_TYPE";
SET UNIQUE = 1 FOR "ROOT_TABLE";
SET UNIQUE = 1 FOR "VIRTUAL_TABLE";
SET UNIQUE = 1 FOR "VIRTUAL_FIELD";
SET UNIQUE = 1 FOR "VIRTUAL_ROW";
SET UNIQUE = 1 FOR "SM_BANNER";
SET UNIQUE = 1 FOR "SM_CHANGE_LOG";
SET UNIQUE = 1 FOR "SM_DA_COLUMN_NOTIFICATION";
SET UNIQUE = 1 FOR "SM_DA_MODE_TEMPLATE";
SET UNIQUE = 1 FOR "SM_DA_WEBSITE_GRP_NOTIFICATION";
SET UNIQUE = 1 FOR "SM_ERROR_LOG";
SET UNIQUE = 1 FOR "SM_FILE_PASSWORD";
SET UNIQUE = 1 FOR "SM_FOOTER";
SET UNIQUE = 1 FOR "SM_GROUP";
SET UNIQUE = 1 FOR "SM_LDAP_BRANCH";
SET UNIQUE = 1 FOR "SM_PAGE_COMP";
SET UNIQUE = 1 FOR "SM_ORG_UNIT";
SET UNIQUE = 1 FOR "SM_SECTION";
SET UNIQUE = 1 FOR "SM_STYLE";
SET UNIQUE = 1 FOR "SM_SECTION_STYLE";
SET UNIQUE = 1 FOR "SM_SECTION_TYPE";
SET UNIQUE = 1 FOR "SM_SITE_FILE";
SET UNIQUE = 1 FOR "SM_SITE_FILE_FOLDER";
SET UNIQUE = 1 FOR "SM_USAGE_LOG";
SET UNIQUE = 1 FOR "SM_USER";
SET UNIQUE = 1 FOR "SM_WEBSITE";
SET UNIQUE = 1 FOR "SM_WEBSITE_CHANGE_LOG";
SET UNIQUE = 1 FOR "SM_WEBSITE_REQUEST";


--
-- Add GVCSiteMaker specific fields to VirutalField
--
ALTER TABLE "VIRTUAL_FIELD" ADD COLUMN "FILE_FKEY" BYTE(24);
ALTER TABLE "VIRTUAL_FIELD" ADD COLUMN "USER_FKEY" BYTE(24);


--
-- Remove nullity constraints on these FK columns as it causes problems with EOF operation ordering during deletion.
--
-- "SM_BANNER"  "WEBSITE_FKEY" NUMERIC;
-- "SM_FOOTER" "WEBSITE_FKEY" NUMERIC;
-- "SM_SECTION_STYLE" "OID_CREATED_BY" NUMERIC;
-- "SM_SECTION_STYLE" "OID_OWN_UNIT" NUMERIC;
-- "SM_STYLE" "OID_CREATED_BY" NUMERIC;
-- "SM_STYLE" "OID_OWN_UNIT" NUMERIC;
-- "SM_USAGE_LOG" "USER_PKEY" NUMERIC;
-- "SM_WEBSITE" "OID_SECTION_STYLE" NUMERIC;


-- 
-- Performance Indexes and Caches
--
CREATE INDEX SM_DA_WEBSITE_GRP_NOTIFICATION     ON SM_DA_WEBSITE_GRP_NOTIFICATION (COMPONENT_ID);
CREATE INDEX SM_FILE_PASSWORD_SITE_FILE_FKEY    ON SM_FILE_PASSWORD (SITE_FILE_PASSWORD_FKEY);
CREATE INDEX SM_GROUP_FILE_FILE_PKEY            ON SM_GROUP_FILE (FILE_PKEY);
CREATE INDEX SM_GROUP_PARENT_WEBSITE            ON SM_GROUP (PARENT_WEBSITE);
CREATE INDEX SM_GROUP_SECTION_SECTION_PKEY      ON SM_GROUP_SECTION (SECTION_PKEY);
CREATE INDEX SM_ORG_UNIT_OID_PARENT_ORG_UNIT    ON SM_ORG_UNIT (OID_PARENT_ORG_UNIT);
CREATE INDEX SM_PAGE_COMP_PARENT_ID             ON SM_PAGE_COMP (PARENT_ID);
CREATE INDEX SM_PAGE_COMP_FILE_ID               ON SM_PAGE_COMP (RELATED_FILE_ID);
CREATE INDEX SM_PAGE_COMP_FIELD_ID              ON SM_PAGE_COMP (FIELD_ID);
CREATE INDEX SM_PAGE_COMP_EMBED_SECTION_FKEY    ON SM_PAGE_COMP (EMBED_SECTION_FKEY);
CREATE INDEX SM_PAGE_COMP_EMBED_WEBSITE_FKEY    ON SM_PAGE_COMP (EMBED_WEBSITE_FKEY);
CREATE INDEX SM_PAGE_COMP_TEMPLATE_OID          ON SM_PAGE_COMP (TEMPLATE_OID);
CREATE INDEX SM_PAGE_COMP_COMPONENT_TYPE        ON SM_PAGE_COMP (COMPONENT_TYPE);
CREATE INDEX SM_SECTION_WEBSITE_FKEY            ON SM_SECTION (WEBSITE_FKEY);
CREATE INDEX SM_SECTION_COMPONENT_ID            ON SM_SECTION (COMPONENT_ID);
CREATE INDEX SM_SECTION_STYLE_OID_OWN_UNIT      ON SM_SECTION_STYLE (OID_OWN_UNIT);
CREATE INDEX SM_SECTION_VERSION_OID_COMPONENT   ON SM_SECTION_VERSION (OID_COMPONENT);
CREATE INDEX SM_SITE_FILE_FOLDER_PARENT_FOLDER  ON SM_SITE_FILE_FOLDER (OID_PARENT_FOLDER);
CREATE INDEX SM_SITE_FILE_FOLDER_WEBSITE_FKEY   ON SM_SITE_FILE_FOLDER (WEBSITE_FKEY);
CREATE INDEX SM_SITE_FILE_OID_SITE_FILE_FOLDER  ON SM_SITE_FILE (OID_SITE_FILE_FOLDER);
CREATE INDEX SM_SITE_FILE_WEBSITE_FKEY          ON SM_SITE_FILE (WEBSITE_FKEY);
CREATE INDEX SM_STYLE_OID_OWN_UNIT              ON SM_STYLE (OID_OWN_UNIT);
CREATE INDEX SM_USER_GROUP_USER_PKEY            ON SM_USER_GROUP (USER_PKEY);
CREATE INDEX SM_USER_ID                         ON SM_USER (USER_ID);
CREATE INDEX SM_USER_ORG_UNIT_FOR_STYLES        ON SM_USER (ORG_UNIT_FOR_STYLES);
CREATE INDEX SM_WEBSITE_OID_PARENT_ORG_UNIT     ON SM_WEBSITE (OID_PARENT_ORG_UNIT);
CREATE INDEX SM_WEBSITE_OID_SECTION_STYLE       ON SM_WEBSITE (OID_SECTION_STYLE);
CREATE INDEX SM_WEBSITE_USER_FKEY               ON SM_WEBSITE (USER_FKEY);
CREATE INDEX CONFIG_GROUP                       ON SM_WEBSITE (GROUP_PKEY);
CREATE INDEX SM_WEBSITE_TABLE_WEBSITE_FKEY      ON SM_WEBSITE_TABLE (WEBSITE_FKEY);

--
-- Case Insensitve Collation for Website SiteID searches
--
CREATE COLLATION CaseInsensitive FOR INFORMATION_SCHEMA.SQL_TEXT FROM EXTERNAL('CaseInsensitive.coll1');
COMMIT;
ALTER COLUMN "sm_website"."site_id" TO COLLATE CASEINSENSITIVE;
COMMIT;
CREATE INDEX SM_WEBSITE_SITE_ID                 ON SM_WEBSITE (SITE_ID);
COMMIT;

CREATE INDEX VIRTUAL_ROW_VIRTUAL_TABLE_ID       ON "VIRTUAL_ROW" (VIRTUAL_TABLE_ID, VIRTUAL_ROW_ID);
CREATE INDEX VIRTUAL_COLUMN_LOOKUP_COLUMN_ID    ON "VIRTUAL_COLUMN" (LOOKUP_COLUMN_ID);
CREATE INDEX VIRTUAL_COLUMN_TABLE_ID            ON "VIRTUAL_COLUMN" (TABLE_ID, COLUMN_ID);
CREATE INDEX VIRTUAL_FIELD_COLUMN_ID            ON "VIRTUAL_FIELD" (VIRTUAL_COLUMN_ID, VIRTUAL_FIELD_ID);
CREATE INDEX VIRTUAL_FIELD_VIRTUAL_ROW_ID       ON "VIRTUAL_FIELD" (VIRTUAL_ROW_ID, VIRTUAL_FIELD_ID);
CREATE INDEX VIRTUAL_FIELD_LOOKUP_VALUE_ID      ON "VIRTUAL_FIELD" ("LOOKUP_VALUE_ID");


ALTER TABLE "GVC_LOOKUP" SET PRESERVE TRUE;
ALTER TABLE "GVC_VA_OBJECT" SET PRESERVE TRUE;
ALTER TABLE "VIRTUAL_COLUMN" SET PRESERVE TRUE;
ALTER TABLE "COLUMN_TYPE" SET PRESERVE TRUE;
ALTER TABLE "ROOT_TABLE" SET PRESERVE TRUE;
ALTER TABLE "VIRTUAL_FIELD" SET PRESERVE TRUE;
ALTER TABLE "VIRTUAL_ROW" SET PRESERVE TRUE;
ALTER TABLE "VIRTUAL_TABLE" SET PRESERVE TRUE;
ALTER TABLE "SM_BANNER" SET PRESERVE TRUE;
ALTER TABLE "SM_SECTION_TYPE" SET PRESERVE TRUE;
ALTER TABLE "SM_ERROR_LOG" SET PRESERVE TRUE;
ALTER TABLE "SM_FILE_PASSWORD" SET PRESERVE TRUE;
ALTER TABLE "SM_FOOTER" SET PRESERVE TRUE;
ALTER TABLE "SM_GROUP" SET PRESERVE TRUE;
ALTER TABLE "SM_GROUP_FILE" SET PRESERVE TRUE;
ALTER TABLE "SM_GROUP_SECTION" SET PRESERVE TRUE;
ALTER TABLE "SM_ORG_UNIT" SET PRESERVE TRUE;
ALTER TABLE "SM_VIRTUAL_TABLE" SET PRESERVE TRUE;
ALTER TABLE "SM_SECTION" SET PRESERVE TRUE;
ALTER TABLE "SM_SECTION_STYLE" SET PRESERVE TRUE;
ALTER TABLE "SM_SITE_FILE" SET PRESERVE TRUE;
ALTER TABLE "SM_SITE_FILE_FOLDER" SET PRESERVE TRUE;
ALTER TABLE "SM_STYLE" SET PRESERVE TRUE;
ALTER TABLE "SM_USAGE_LOG" SET PRESERVE TRUE;
ALTER TABLE "SM_USER" SET PRESERVE TRUE;
ALTER TABLE "SM_USER_GROUP" SET PRESERVE TRUE;
ALTER TABLE "SM_WEBSITE" SET PRESERVE TRUE;
ALTER TABLE "SM_WEBSITE_TABLE" SET PRESERVE TRUE;
ALTER TABLE "SM_PAGE_COMP" SET PRESERVE TRUE;
ALTER TABLE "SM_DA_MODE_TEMPLATE" SET PRESERVE TRUE;
ALTER TABLE "SM_LDAP_BRANCH" SET PRESERVE TRUE;
ALTER TABLE "SM_DA_WEBSITE_GRP_NOTIFICATION" SET PRESERVE TRUE;
ALTER TABLE "SM_DA_COLUMN_NOTIFICATION" SET PRESERVE TRUE;
ALTER TABLE "SM_WEBSITE_REQUEST" SET PRESERVE TRUE;
ALTER TABLE "SM_CHANGE_LOG" SET PRESERVE TRUE;
ALTER TABLE "SM_WEBSITE_CHANGE_LOG" SET PRESERVE TRUE;
ALTER TABLE "SM_ORG_UNIT_USER" SET PRESERVE TRUE;


ALTER TABLE "VIRTUAL_COLUMN" SET CACHE(1000, 1000000, 100);
ALTER TABLE "VIRTUAL_FIELD" SET CACHE(10000, 10000000, 100);
ALTER TABLE "VIRTUAL_ROW" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_BANNER" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_FOOTER" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_GROUP_FILE" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_GROUP_SECTION" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_SECTION" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_SITE_FILE" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_SITE_FILE_FOLDER" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_USER" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_WEBSITE" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_WEBSITE_TABLE" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_PAGE_COMP" SET CACHE(1000, 1000000, 100);
ALTER TABLE "SM_DA_MODE_TEMPLATE" SET CACHE(1000, 1000000, 100);

COMMIT;
