SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

CREATE TABLE "VIRTUAL_COLUMN" (
	"COLUMN_ID" INTEGER NOT NULL,
	"COLUMN_TYPE_ID" INTEGER NOT NULL,
	"DATE_CREATED" TIMESTAMP NOT NULL,
	"IS_SYSTEM_COLUMN" CHARACTER(1) NOT NULL,
	"NAME" VARCHAR(100) NOT NULL,
	"RESTRICTING_VALUE" VARCHAR(50) NOT NULL,
	"TABLE_ID" INTEGER NOT NULL,
	"TEXT_DESCRIPTION" VARCHAR(1999),
	"LOOKUP_COLUMN_ID" INTEGER,
	"EXPRESSION" VARCHAR(2000000)
);

CREATE TABLE "COLUMN_TYPE" (
	"ENTITY_NAME_RESTRICTOR" VARCHAR(50) NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"TEXT_DESCRIPTION" VARCHAR(1999),
	"the_id" INTEGER NOT NULL
);

CREATE TABLE "ROOT_TABLE" (
	"DATE_CREATED" TIMESTAMP NOT NULL,
	"DATE_MODIFIED" TIMESTAMP NOT NULL,
	"NAME" VARCHAR(100) NOT NULL,
	"TABLE_ID" INTEGER NOT NULL,
	"TEXT_DESCRIPTION" VARCHAR(1999)
);

CREATE TABLE "VIRTUAL_FIELD" (
	"BOOLEAN_VALUE" VARCHAR(5),
	"RESTRICTING_VALUE" VARCHAR(50) NOT NULL,
	"VIRTUAL_COLUMN_ID" INTEGER NOT NULL,
	"VIRTUAL_FIELD_ID" INTEGER NOT NULL,
	"VIRTUAL_ROW_ID" INTEGER NOT NULL,
	"LOOKUP_VALUE_ID" INTEGER,
	"LONG_STRING_VALUE" CLOB,
	"NUMBER_VALUE" DECIMAL(30,10),
	"STRING_VALUE" VARCHAR(2000000),
	"TIMESTAMP_VALUE" TIMESTAMP
);

CREATE TABLE "VIRTUAL_ROW" (
	"VIRTUAL_ROW_ID" INTEGER NOT NULL,
	"VIRTUAL_TABLE_ID" INTEGER NOT NULL
);

CREATE TABLE "VIRTUAL_TABLE" (
	"DATE_CREATED" TIMESTAMP NOT NULL,
	"DATE_MODIFIED" TIMESTAMP NOT NULL,
	"NAME" VARCHAR(100) NOT NULL,
	"TABLE_ID" INTEGER NOT NULL,
	"TEXT_DESCRIPTION" VARCHAR(1999)
);

SET UNIQUE = 1000000 FOR "VIRTUAL_COLUMN";

SET UNIQUE = 1000000 FOR "VIRTUAL_COLUMN";

SET UNIQUE = 1000000 FOR "VIRTUAL_COLUMN";

SET UNIQUE = 1000000 FOR "COLUMN_TYPE";

SET UNIQUE = 1000000 FOR "VIRTUAL_TABLE";

SET UNIQUE = 1000000 FOR "ROOT_TABLE";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_FIELD";

SET UNIQUE = 1000000 FOR "VIRTUAL_ROW";

ALTER TABLE "VIRTUAL_COLUMN" ADD PRIMARY KEY ("COLUMN_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "COLUMN_TYPE" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ROOT_TABLE" ADD PRIMARY KEY ("TABLE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "VIRTUAL_FIELD" ADD PRIMARY KEY ("VIRTUAL_FIELD_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "VIRTUAL_ROW" ADD PRIMARY KEY ("VIRTUAL_ROW_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "VIRTUAL_TABLE" ADD PRIMARY KEY ("TABLE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "VIRTUAL_COLUMN" ADD FOREIGN KEY ("COLUMN_TYPE_ID") REFERENCES "COLUMN_TYPE" ("THE_ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "VIRTUAL_FIELD" ADD FOREIGN KEY ("VIRTUAL_ROW_ID") REFERENCES "VIRTUAL_ROW" ("VIRTUAL_ROW_ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "VIRTUAL_ROW" ADD FOREIGN KEY ("VIRTUAL_TABLE_ID") REFERENCES "VIRTUAL_TABLE" ("TABLE_ID") DEFERRABLE INITIALLY DEFERRED;

COMMIT;

