SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

-- The 'Drop Primary Key Support' option is unavailable.;

DROP TABLE "VIRTUAL_COLUMN" CASCADE;

DROP TABLE "COLUMN_TYPE" CASCADE;

DROP TABLE "ROOT_TABLE" CASCADE;

DROP TABLE "VIRTUAL_FIELD" CASCADE;

DROP TABLE "VIRTUAL_ROW" CASCADE;

DROP TABLE "VIRTUAL_TABLE" CASCADE;


COMMIT;

