--
-- These indexes are needed for performance reasons.
--
CREATE INDEX VIRTUAL_ROW_VIRTUAL_TABLE_ID       ON "VIRTUAL_ROW"  (VIRTUAL_TABLE_ID, VIRTUAL_ROW_ID);
CREATE INDEX VIRTUAL_COLUMN_LOOKUP_COLUMN_ID    ON "VIRTUAL_COLUMN" (LOOKUP_COLUMN_ID);
CREATE INDEX VIRTUAL_COLUMN_TABLE_ID            ON "VIRTUAL_COLUMN" (TABLE_ID, COLUMN_ID);
CREATE INDEX VIRTUAL_FIELD_COLUMN_ID            ON "VIRTUAL_FIELD"  (VIRTUAL_COLUMN_ID, VIRTUAL_FIELD_ID);
CREATE INDEX VIRTUAL_FIELD_VIRTUAL_ROW_ID       ON "VIRTUAL_FIELD"  (VIRTUAL_ROW_ID, VIRTUAL_FIELD_ID);
CREATE INDEX VIRTUAL_FIELD_LOOKUP_VALUE_ID      ON "VIRTUAL_FIELD"  ("LOOKUP_VALUE_ID");
