
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC, READ WRITE;
SET COMMIT FALSE;

DELETE FROM "COLUMN_TYPE";       
SET UNIQUE = 1 FOR "COLUMN_TYPE";

COMMIT;

INSERT INTO "COLUMN_TYPE" ("THE_ID", "NAME", "ENTITY_NAME_RESTRICTOR", "TEXT_DESCRIPTION") VALUES ((SELECT UNIQUE FROM GVC_LOOKUP), 'String', '', NULL);
INSERT INTO "COLUMN_TYPE" ("THE_ID", "NAME", "ENTITY_NAME_RESTRICTOR", "TEXT_DESCRIPTION") VALUES ((SELECT UNIQUE FROM GVC_LOOKUP), 'Memo', '', NULL);
INSERT INTO "COLUMN_TYPE" ("THE_ID", "NAME", "ENTITY_NAME_RESTRICTOR", "TEXT_DESCRIPTION") VALUES ((SELECT UNIQUE FROM GVC_LOOKUP), 'Timestamp', '', NULL);
INSERT INTO "COLUMN_TYPE" ("THE_ID", "NAME", "ENTITY_NAME_RESTRICTOR", "TEXT_DESCRIPTION") VALUES ((SELECT UNIQUE FROM GVC_LOOKUP), 'Lookup', 'Lookup', NULL);
INSERT INTO "COLUMN_TYPE" ("THE_ID", "NAME", "ENTITY_NAME_RESTRICTOR", "TEXT_DESCRIPTION") VALUES ((SELECT UNIQUE FROM GVC_LOOKUP), 'Number', '', NULL);
INSERT INTO "COLUMN_TYPE" ("THE_ID", "NAME", "ENTITY_NAME_RESTRICTOR", "TEXT_DESCRIPTION") VALUES ((SELECT UNIQUE FROM GVC_LOOKUP), 'Boolean', '', NULL);
INSERT INTO "COLUMN_TYPE" ("THE_ID", "NAME", "ENTITY_NAME_RESTRICTOR", "TEXT_DESCRIPTION") VALUES ((SELECT UNIQUE FROM GVC_LOOKUP), 'Calculated', 'Calculated', NULL);

COMMIT;

