-- Written by FrontBase Server - 4.2.9
-- Created by FrontBase Server - 4.2.9
;
--SET CATALOG 'GVCSITEMAKER-UMICH'
;
SET DATABASE IDENTITY '31bc5e3d01004f654c020a0a';

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;
CREATE USER "UMICH";
COMMIT;

DELETE FROM INFORMATION_SCHEMA."INFORMATION_SCHEMA_CATALOG_NAME";
INSERT INTO INFORMATION_SCHEMA."INFORMATION_SCHEMA_CATALOG_NAME" FROM INPUT(FILE = '/tmp/um//1_0', TYPE = 'FrontBase');

DELETE FROM INFORMATION_SCHEMA."BLACK_AND_WHITE_LIST";
INSERT INTO INFORMATION_SCHEMA."BLACK_AND_WHITE_LIST" FROM INPUT(FILE = '/tmp/um//1_24', TYPE = 'FrontBase');

DROP SCHEMA "_SYSTEM" CASCADE;
COMMIT;
CREATE SCHEMA "_SYSTEM" AUTHORIZATION "_SYSTEM";
COMMIT;

CREATE SCHEMA "UMICH" AUTHORIZATION "UMICH"
CREATE COLLATION "CASEINSENSITIVE" FOR "INFORMATION_SCHEMA"."SQL_TEXT" FROM EXTERNAL('CaseInsensitive.coll1')


CREATE TABLE "SM_BANNER"(
   "BANNER_TEXT" CHARACTER VARYING(300),
   "WEBSITE_FKEY" BYTE(24)
)

CREATE TABLE "SM_DA_MODE_TEMPLATE"(
   "HTML" CLOB,
   "OID" BYTE(24)
)

CREATE TABLE "SM_ERROR_LOG"(
   "APP_NAME" CHARACTER VARYING(100),
   "COMPONENT_NAME" CHARACTER VARYING(100),
   "EVENT_DATE" TIMESTAMP WITH TIME ZONE,
   "EXCEPTION_MESSAGE" CHARACTER VARYING(1999),
   "HOST_NAME" CHARACTER VARYING(100),
   "LOG_TYPE" CHARACTER VARYING(100),
   "OID" BYTE(24),
   "PAGE_NAME" CHARACTER VARYING(100),
   "STACK_TRACE" CLOB,
   "USER_ID" CHARACTER VARYING(100),
   "REQUEST" CLOB
)

CREATE TABLE "SM_FILE_PASSWORD"(
   "EXPIRATION_DATE" TIMESTAMP WITH TIME ZONE,
   "FILE_PASSWORD_PKEY" BYTE(24),
   "PASSWORD" CHARACTER VARYING(50),
   "SITE_FILE_PASSWORD_FKEY" BYTE(24)
)

CREATE TABLE "SM_FOOTER"(
   "LINK_TEXT_1" CHARACTER VARYING(300),
   "LINK_TEXT_2" CHARACTER VARYING(300),
   "LINK_TEXT_3" CHARACTER VARYING(300),
   "LINK_TEXT_4" CHARACTER VARYING(300),
   "LINK_URL_1" CHARACTER VARYING(255),
   "LINK_URL_2" CHARACTER VARYING(255),
   "LINK_URL_3" CHARACTER VARYING(255),
   "LINK_URL_4" CHARACTER VARYING(255),
   "WEBSITE_FKEY" BYTE(24),
   "CUSTOM_FOOTER" CLOB
)

CREATE TABLE "SM_GROUP"(
   "CREATION_DATE" TIMESTAMP WITH TIME ZONE,
   "GROUP_PKEY" BYTE(24),
   "GROUP_NAME" CHARACTER VARYING(150),
   "TYPE" CHARACTER VARYING(25),
   "PARENT_WEBSITE" BYTE(24),
   "OID_LDAP_BRANCH" BYTE(24),
   "LDAP_GROUP_NAME" CHARACTER VARYING(255),
   "SECRET" CHARACTER VARYING(255),
   "OID_SECTION_STYLE" BYTE(24)
)

CREATE TABLE "SM_GROUP_FILE"(
   "FILE_PKEY" BYTE(24),
   "GROUP_PKEY" BYTE(24)
)

CREATE TABLE "SM_GROUP_SECTION"(
   "GROUP_PKEY" BYTE(24),
   "SECTION_PKEY" BYTE(24)
)

CREATE TABLE "SM_PAGE_COMP"(
   "BINDINGS" CLOB,
   "COMPONENT_ID" BYTE(24),
   "COMPONENT_TYPE" CHARACTER VARYING(255),
   "DATE_MODIFIED" TIMESTAMP WITH TIME ZONE,
   "PARENT_ID" BYTE(24),
   "RELATED_FILE_ID" BYTE(24),
   "SUB_TYPE" CHARACTER VARYING(50),
   "TYPE" CHARACTER VARYING(50),
   "EMBED_SECTION_FKEY" BYTE(24),
   "EMBED_WEBSITE_FKEY" BYTE(24),
   "TABLE_ID" BYTE(24),
   "COLUMN_ID" BYTE(24),
   "FIELD_ID" BYTE(24),
   "TEMPLATE_OID" BYTE(24),
   "RELATED_SECTION_ID" BYTE(24)
)

CREATE TABLE "SM_ORG_UNIT"(
   "DEPTH" NUMERIC,
   "FILE_SIZE_QUOTA" NUMERIC,
   "FILE_SIZE_USAGE" NUMERIC,
   "IN_PUBLIC_LIST" CHARACTER(1),
   "OID" BYTE(24),
   "OID_PARENT_ORG_UNIT" BYTE(24),
   "UNIT_NAME" CHARACTER VARYING(765),
   "WEBSITE_CREATION_MESSAGE" CLOB
)

CREATE TABLE "SM_SECTION"(
   "COMPONENT_ID" BYTE(24),
   "DETAILS" CHARACTER VARYING(765),
   "NAME" CHARACTER VARYING(150),
   "NORMAL_NAME" CHARACTER VARYING(150),
   "OID_SECTION_STYLE" BYTE(24),
   "SECTION_ORDER" NUMERIC,
   "SECTION_PKEY" BYTE(24),
   "WEBSITE_FKEY" BYTE(24),
   "TYPE_OID" BYTE(24),
   "IS_NAVIGABLE" CHARACTER(1),
   "INDENTATION" NUMERIC,
   "REQUIRE_HTTPS_ACCESS" CHARACTER(1),
   "IS_VERSIONING" CHARACTER(1),
   "MIME_TYPE" CHARACTER VARYING(50),
   "IS_AUTO_VERSIONING" CHARACTER(1)
)

CREATE TABLE "SM_SECTION_STYLE"(
   "BANNER_COMP" CHARACTER VARYING(50),
   "DATE_CREATED" TIMESTAMP WITH TIME ZONE,
   "DATE_MODIFIED" TIMESTAMP WITH TIME ZONE,
   "DEFAULT_STYLE" CHARACTER(1),
   "FOOTER_COMP" CHARACTER VARYING(50),
   "NAME" CHARACTER VARYING(100),
   "NAVBAR_COMP" CHARACTER VARYING(50),
   "NOTES" CHARACTER VARYING(6000),
   "OID" BYTE(24),
   "OID_CREATED_BY" BYTE(24),
   "OID_MODIFIED_BY" BYTE(24),
   "OID_OWN_UNIT" BYTE(24),
   "PAGE_SCFLD_COMP" CHARACTER VARYING(50),
   "PUBLISHED" CHARACTER(1),
   "RESOURCE_DIR" CHARACTER VARYING(100),
   "SECT_CONT_COMP" CHARACTER VARYING(50),
   "STYLE_ID" CHARACTER VARYING(50),
   "TEMPLATE" CLOB,
   "RELATED_CSS_URL" CHARACTER VARYING(100)
)

CREATE TABLE "SM_SITE_FILE"(
   "FILE_DESCRIPTION" CHARACTER VARYING(6000),
   "FILE_PKEY" BYTE(24),
   "FILE_SIZE_USAGE" NUMERIC,
   "FILENAME" CHARACTER VARYING(300),
   "MIME_TYPE" CHARACTER VARYING(50),
   "UPLOAD_DATE" TIMESTAMP WITH TIME ZONE,
   "UPLOADED_FILENAME" CHARACTER VARYING(300),
   "WEBSITE_FKEY" BYTE(24),
   "OID_SITE_FILE_FOLDER" BYTE(24),
   "SHORT_NAME" CHARACTER VARYING(300)
)

CREATE TABLE "SM_STYLE"(
   "DATE_CREATED" TIMESTAMP WITH TIME ZONE,
   "DATE_MODIFIED" TIMESTAMP WITH TIME ZONE,
   "NAME" CHARACTER VARYING(300),
   "NOTES" CHARACTER VARYING(6000),
   "OID" BYTE(24),
   "OID_CREATED_BY" BYTE(24),
   "OID_MODIFIED_BY" BYTE(24),
   "OID_OWN_UNIT" BYTE(24),
   "PUBLISHED" CHARACTER(1),
   "STYLE_ID" CHARACTER VARYING(150),
   "TEMPLATE" CLOB
)

CREATE TABLE "SM_USAGE_LOG"(
   "ACCESS_TIME" TIMESTAMP WITH TIME ZONE,
   "USAGE_LOG_PKEY" BYTE(24),
   "USER_PKEY" BYTE(24)
)

CREATE TABLE "SM_USER"(
   "ORG_UNIT_FOR_STYLES" BYTE(24),
   "PASSWORD" CHARACTER VARYING(300),
   "USER_ID" CHARACTER VARYING(300),
   "USER_PKEY" BYTE(24)
)

CREATE TABLE "SM_USER_GROUP"(
   "GROUP_PKEY" BYTE(24),
   "USER_PKEY" BYTE(24)
)

CREATE TABLE "SM_WEBSITE"(
   "CAN_REPLICATE" CHARACTER(1),
   "CONTACT_EMAIL" CHARACTER VARYING(300),
   "CONTACT_FAX" CHARACTER VARYING(75),
   "CONTACT_NAME" CHARACTER VARYING(300),
   "CONTACT_PHONE" CHARACTER VARYING(75),
   "DATE_LAST_MODIFIED" TIMESTAMP,
   "FILE_SIZE_USAGE" NUMERIC,
   "GROUP_PKEY" BYTE(24),
   "MEG_QUOTA" NUMERIC,
   "OID_PARENT_ORG_UNIT" BYTE(24),
   "OID_SECTION_STYLE" BYTE(24),
   "PUBLICATION_PERMITTED" CHARACTER(1),
   "PUBLISHED" CHARACTER(1),
   "REDIRECT_URL" CHARACTER VARYING(255),
   "SHOW_BANNER" CHARACTER(1),
   "SHOW_FOOTER" CHARACTER(1),
   "SHOW_NAVBAR" CHARACTER(1),
   "SITE_ID" CHARACTER VARYING(150) COLLATE "UMICH"."CASEINSENSITIVE",
   "USER_FKEY" BYTE(24),
   "WEBSITE_PKEY" BYTE(24),
   "DATE_CREATED" TIMESTAMP,
   "SHOW_LOGIN_LOGOUT_LINKS" CHARACTER(1),
   "CUSTOM_HEADER_CONTENT" CLOB
)

CREATE TABLE "GVC_LOOKUP"(
   "NAME" CHARACTER VARYING(50),
   "THE_ID" BYTE(24)
)

CREATE TABLE "GVC_VA_OBJECT"(
   "IS_ACTIVE" CHARACTER(1),
   "THE_ID" BYTE(24)
)

CREATE TABLE "VIRTUAL_COLUMN"(
   "COLUMN_ID" BYTE(24),
   "COLUMN_TYPE_ID" BYTE(24),
   "DATE_CREATED" TIMESTAMP WITH TIME ZONE,
   "IS_SYSTEM_COLUMN" CHARACTER(1),
   "NAME" CHARACTER VARYING(100),
   "RESTRICTING_VALUE" CHARACTER VARYING(50),
   "TABLE_ID" BYTE(24),
   "TEXT_DESCRIPTION" CHARACTER VARYING(6000),
   "LOOKUP_COLUMN_ID" BYTE(24),
   "EXPRESSION" CHARACTER VARYING(2000000)
)

CREATE TABLE "COLUMN_TYPE"(
   "ENTITY_NAME_RESTRICTOR" CHARACTER VARYING(50),
   "NAME" CHARACTER VARYING(50),
   "TEXT_DESCRIPTION" CHARACTER VARYING(1999),
   "THE_ID" BYTE(24)
)

CREATE TABLE "ROOT_TABLE"(
   "DATE_CREATED" TIMESTAMP WITH TIME ZONE,
   "DATE_MODIFIED" TIMESTAMP WITH TIME ZONE,
   "NAME" CHARACTER VARYING(100),
   "TABLE_ID" BYTE(24),
   "TEXT_DESCRIPTION" CHARACTER VARYING(1999)
)

CREATE TABLE "VIRTUAL_FIELD"(
   "RESTRICTING_VALUE" CHARACTER VARYING(50),
   "VIRTUAL_COLUMN_ID" BYTE(24),
   "VIRTUAL_FIELD_ID" BYTE(24),
   "VIRTUAL_ROW_ID" BYTE(24),
   "LOOKUP_VALUE_ID" BYTE(24),
   "LONG_STRING_VALUE" CLOB,
   "NUMBER_VALUE" DECIMAL(30,10),
   "STRING_VALUE" CHARACTER VARYING(6000000),
   "TIMESTAMP_VALUE" TIMESTAMP,
   "FILE_FKEY" BYTE(24),
   "USER_FKEY" BYTE(24),
   "BOOLEAN_VALUE" CHARACTER VARYING(5)
)

CREATE TABLE "VIRTUAL_ROW"(
   "VIRTUAL_ROW_ID" BYTE(24),
   "VIRTUAL_TABLE_ID" BYTE(24)
)

CREATE TABLE "VIRTUAL_TABLE"(
   "DATE_CREATED" TIMESTAMP,
   "DATE_MODIFIED" TIMESTAMP,
   "NAME" CHARACTER VARYING(300),
   "TABLE_ID" BYTE(24),
   "TEXT_DESCRIPTION" CHARACTER VARYING(6000)
)

CREATE TABLE "SM_SITE_FILE_FOLDER"(
   "NAME" CHARACTER VARYING(765),
   "OID" BYTE(24),
   "OID_PARENT_FOLDER" BYTE(24),
   "WEBSITE_FKEY" BYTE(24)
)

CREATE TABLE "SM_SECTION_TYPE"(
   "EDITOR_NAME" CHARACTER VARYING(100),
   "NAME" CHARACTER VARYING(100),
   "OID" BYTE(24),
   "ORDER" NUMERIC,
   "PAGE_COMP_ENTITY" CHARACTER VARYING(100),
   "KEY" CHARACTER VARYING(50)
)

CREATE TABLE "SM_WEBSITE_TABLE"(
   "TABLE_ID" BYTE(24),
   "WEBSITE_FKEY" BYTE(24)
)

CREATE TABLE "SM_VIRTUAL_TABLE"(
   "CREATE_USER_FKEY" BYTE(24),
   "DATE_CREATED" TIMESTAMP WITH TIME ZONE,
   "DATE_MODIFIED" TIMESTAMP WITH TIME ZONE,
   "NAME" CHARACTER VARYING(300),
   "TABLE_ID" BYTE(24),
   "TEXT_DESCRIPTION" CHARACTER VARYING(6000),
   "UPDATE_USER_FKEY" BYTE(24)
)

CREATE TABLE "SM_LDAP_BRANCH"(
   "DISPLAY_NAME" CHARACTER VARYING(100),
   "DISPLAY_ORDER" INTEGER,
   "GROUP_SUBTREE" CHARACTER VARYING(100),
   "INSTRUCTIONS" CHARACTER VARYING(1999),
   "LDAP_ENTITY_NAME" CHARACTER VARYING(50),
   "OID" BYTE(24),
   "USER_ID_ATTR" CHARACTER VARYING(50),
   "USER_SUBTREE" CHARACTER VARYING(100)
)

CREATE TABLE "SM_DA_WEBSITE_GRP_NOTIFICATION"(
   "GROUP_PKEY" BYTE(24),
   "COMPONENT_ID" BYTE(24)
)

CREATE TABLE "SM_DA_COLUMN_NOTIFICATION"(
   "COMPONENT_ID" BYTE(24),
   "COLUMN_COMPONENT_ID" BYTE(24)
)

CREATE TABLE "SM_WEBSITE_REQUEST"(
   "ADMINISTRATIVE_NOTES" CLOB,
   "DATE_REQUESTED" TIMESTAMP WITH TIME ZONE,
   "DATE_RESOLVED" TIMESTAMP WITH TIME ZONE,
   "OID" BYTE(24),
   "ORG_UNIT_OID" BYTE(24),
   "REQUESTOR_NOTE" CHARACTER VARYING(1999),
   "SITE_ID" CHARACTER VARYING(50),
   "USER_FKEY" BYTE(24),
   "WEBSITE_FKEY" BYTE(24)
)

CREATE TABLE "SM_CHANGE_LOG"(
   "CHANGES" CHARACTER VARYING(1999),
   "DATE_RECORDED" TIMESTAMP WITH TIME ZONE,
   "NOTES" CHARACTER VARYING(1999),
   "OID" BYTE(24),
   "USER_FKEY" BYTE(24)
)

CREATE TABLE "SM_WEBSITE_CHANGE_LOG"(
   "CHANGES" CHARACTER VARYING(1999),
   "DATE_RECORDED" TIMESTAMP WITH TIME ZONE,
   "NOTES" CHARACTER VARYING(1999),
   "OID" BYTE(24),
   "USER_FKEY" BYTE(24),
   "WEBSITE_FKEY" BYTE(24)
)

CREATE TABLE "SM_ORG_UNIT_USER"(
   "ORG_UNIT_OID" BYTE(24),
   "USER_PKEY" BYTE(24)
)

CREATE TABLE "TASK_STATUS"(
   "KEY" CHARACTER VARYING(50),
   "NAME" CHARACTER VARYING(50),
   "THE_ID" BYTE(24)
)

CREATE TABLE "TASK"(
   "CREATED_DATE" TIMESTAMP WITH TIME ZONE,
   "DETAILS" CHARACTER VARYING(255),
   "FAILURE_REASON" CHARACTER VARYING(1999),
   "IS_NAVIGABLE" CHARACTER(1),
   "RELATED_SECTION_ID" BYTE(24),
   "SOURCE_SECTION_ID" BYTE(24),
   "STATUS_ID" BYTE(24),
   "TASK_ID" BYTE(24),
   "TASK_TYPE" CHARACTER VARYING(255),
   "USER_ID" BYTE(24),
   "BINDINGS" CLOB,
   "RELATED_TABLE_ID" BYTE(24),
   "RELATED_SITE_FILE_FOLDER_ID" BYTE(24),
   "RELATED_SITE_FILE_ID" BYTE(24),
   "ORG_UNIT_ID" BYTE(24),
   "REQUEST_ID" BYTE(24)
)

CREATE TABLE "SM_SECTION_CONTRIBUTOR_GROUP"(
   "GROUP_PKEY" BYTE(24),
   "SECTION_PKEY" BYTE(24)
)

CREATE TABLE "SM_SECTION_EDITOR_GROUP"(
   "GROUP_PKEY" BYTE(24),
   "SECTION_PKEY" BYTE(24)
)

CREATE TABLE "SM_SECTION_VERSION"(
   "CREATED_DATE" TIMESTAMP,
   "DETAILS" CHARACTER VARYING(255),
   "IS_LOCKED" CHARACTER(1),
   "MODIFIED_DATE" TIMESTAMP,
   "NAME" CHARACTER VARYING(50),
   "OID_COMPONENT" BYTE(24),
   "OID_CREATED_BY" BYTE(24),
   "OID_MODIFIED_BY" BYTE(24),
   "OID_SECTION" BYTE(24),
   "VERSION_NUMBER" NUMERIC,
   "VERSION_PKEY" BYTE(24),
   "COMPONENT_ORDER" INTEGER
)

CREATE TABLE "TASK_SECTION"(
   "TASK_ID" BYTE(24),
   "SECTION_ID" BYTE(24)
)

CREATE TABLE "TASK_TABLE"(
   "TABLE_ID" BYTE(24),
   "TASK_ID" BYTE(24)
)
;
COMMIT;

SET SESSION AUTHORIZATION "UMICH";
ALTER TABLE "UMICH"."SM_BANNER" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_BANNER" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_BANNER" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_BANNER" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_DA_MODE_TEMPLATE" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_DA_MODE_TEMPLATE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_DA_MODE_TEMPLATE" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_ERROR_LOG" SET CACHE(0,0,0);
ALTER TABLE "UMICH"."SM_ERROR_LOG" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_ERROR_LOG" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_ERROR_LOG" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_FILE_PASSWORD" SET CACHE(100,10000,100);
ALTER TABLE "UMICH"."SM_FILE_PASSWORD" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_FILE_PASSWORD" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_FILE_PASSWORD" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_FOOTER" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_FOOTER" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_FOOTER" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_FOOTER" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_GROUP" SET CACHE(1000,100000,100);
ALTER TABLE "UMICH"."SM_GROUP" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_GROUP" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_GROUP" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_GROUP_FILE" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_GROUP_FILE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_GROUP_FILE" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_GROUP_SECTION" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_GROUP_SECTION" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_GROUP_SECTION" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_PAGE_COMP" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_PAGE_COMP" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_PAGE_COMP" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_PAGE_COMP" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_ORG_UNIT" SET CACHE(100,1000,100);
ALTER TABLE "UMICH"."SM_ORG_UNIT" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_ORG_UNIT" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_ORG_UNIT" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_SECTION" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_SECTION" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_SECTION" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_SECTION" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_SECTION_STYLE" SET CACHE(1000,100000,100);
ALTER TABLE "UMICH"."SM_SECTION_STYLE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_SECTION_STYLE" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_SECTION_STYLE" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_SITE_FILE" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_SITE_FILE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_SITE_FILE" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_SITE_FILE" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_STYLE" SET CACHE(10,1000,100);
ALTER TABLE "UMICH"."SM_STYLE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_STYLE" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_STYLE" SET INDEX PRESERVE SPACE;
ALTER TABLE "UMICH"."SM_USAGE_LOG" SET CACHE(10000,1000000,100);
ALTER TABLE "UMICH"."SM_USAGE_LOG" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_USAGE_LOG" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_USER" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_USER" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_USER" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_USER" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_USER_GROUP" SET CACHE(1000,100000,100);
ALTER TABLE "UMICH"."SM_USER_GROUP" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_USER_GROUP" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_WEBSITE" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_WEBSITE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_WEBSITE" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_WEBSITE" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."GVC_LOOKUP" SET CACHE(0,0,0);
ALTER TABLE "UMICH"."GVC_LOOKUP" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."GVC_LOOKUP" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."GVC_LOOKUP" SET INDEX PRESERVE SPACE;
ALTER TABLE "UMICH"."GVC_VA_OBJECT" SET CACHE(0,0,0);
ALTER TABLE "UMICH"."GVC_VA_OBJECT" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."GVC_VA_OBJECT" SET INDEX PRESERVE SPACE;
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."COLUMN_TYPE" SET CACHE(1,100,100);
ALTER TABLE "UMICH"."COLUMN_TYPE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."COLUMN_TYPE" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."COLUMN_TYPE" SET INDEX PRESERVE SPACE;
ALTER TABLE "UMICH"."ROOT_TABLE" SET CACHE(0,0,0);
ALTER TABLE "UMICH"."ROOT_TABLE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."ROOT_TABLE" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."ROOT_TABLE" SET INDEX PRESERVE SPACE;
ALTER TABLE "UMICH"."VIRTUAL_FIELD" SET CACHE(10000,10000000,100);
ALTER TABLE "UMICH"."VIRTUAL_FIELD" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."VIRTUAL_FIELD" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."VIRTUAL_FIELD" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."VIRTUAL_ROW" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."VIRTUAL_ROW" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."VIRTUAL_ROW" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."VIRTUAL_TABLE" SET CACHE(0,0,0);
ALTER TABLE "UMICH"."VIRTUAL_TABLE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."VIRTUAL_TABLE" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."VIRTUAL_TABLE" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_SITE_FILE_FOLDER" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_SITE_FILE_FOLDER" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_SITE_FILE_FOLDER" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_SITE_FILE_FOLDER" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_SECTION_TYPE" SET CACHE(1,100,100);
ALTER TABLE "UMICH"."SM_SECTION_TYPE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_SECTION_TYPE" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_SECTION_TYPE" SET INDEX PRESERVE SPACE;
ALTER TABLE "UMICH"."SM_WEBSITE_TABLE" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_WEBSITE_TABLE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_WEBSITE_TABLE" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" SET CACHE(1000,100000,100);
ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_LDAP_BRANCH" SET CACHE(1,10,100);
ALTER TABLE "UMICH"."SM_LDAP_BRANCH" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_LDAP_BRANCH" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_LDAP_BRANCH" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_DA_WEBSITE_GRP_NOTIFICATION" SET CACHE(100,1000,100);
ALTER TABLE "UMICH"."SM_DA_WEBSITE_GRP_NOTIFICATION" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_DA_WEBSITE_GRP_NOTIFICATION" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_DA_COLUMN_NOTIFICATION" SET CACHE(100,10000,100);
ALTER TABLE "UMICH"."SM_DA_COLUMN_NOTIFICATION" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_DA_COLUMN_NOTIFICATION" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" SET CACHE(100,1000,100);
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_CHANGE_LOG" SET CACHE(0,0,0);
ALTER TABLE "UMICH"."SM_CHANGE_LOG" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_CHANGE_LOG" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_CHANGE_LOG" SET INDEX PRESERVE SPACE;
ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" SET CACHE(100,10000,100);
ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_ORG_UNIT_USER" SET CACHE(100,10000,100);
ALTER TABLE "UMICH"."SM_ORG_UNIT_USER" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_ORG_UNIT_USER" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."TASK_STATUS" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."TASK_STATUS" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."TASK" SET CACHE(100,10000,100);
ALTER TABLE "UMICH"."TASK" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."TASK" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."TASK" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_SECTION_CONTRIBUTOR_GROUP" SET CACHE(100,10000,100);
ALTER TABLE "UMICH"."SM_SECTION_CONTRIBUTOR_GROUP" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_SECTION_CONTRIBUTOR_GROUP" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_SECTION_EDITOR_GROUP" SET CACHE(100,10000,100);
ALTER TABLE "UMICH"."SM_SECTION_EDITOR_GROUP" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_SECTION_EDITOR_GROUP" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."SM_SECTION_VERSION" SET CACHE(1000,1000000,100);
ALTER TABLE "UMICH"."SM_SECTION_VERSION" SET PRESERVE TRUE;
ALTER TABLE "UMICH"."SM_SECTION_VERSION" SET CHAR CACHE(2000, 20000, 80);
ALTER TABLE "UMICH"."SM_SECTION_VERSION" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."TASK_SECTION" SET INDEX PRESERVE TIME;
ALTER TABLE "UMICH"."TASK_TABLE" SET INDEX PRESERVE TIME;
INSERT INTO "UMICH"."SM_BANNER" FROM INPUT(FILE = '/tmp/um//3_37', TYPE = 'FrontBase');
SET UNIQUE=3598 FOR "UMICH"."SM_BANNER";
ALTER TABLE "UMICH"."SM_BANNER" ADD PRIMARY KEY("WEBSITE_FKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_DA_MODE_TEMPLATE" FROM INPUT(FILE = '/tmp/um//3_38', TYPE = 'FrontBase');
SET UNIQUE=1023851 FOR "UMICH"."SM_DA_MODE_TEMPLATE";
ALTER TABLE "UMICH"."SM_DA_MODE_TEMPLATE" ADD PRIMARY KEY("OID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_ERROR_LOG" FROM INPUT(FILE = '/tmp/um//3_39', TYPE = 'FrontBase');
SET UNIQUE=220825 FOR "UMICH"."SM_ERROR_LOG";
ALTER TABLE "UMICH"."SM_ERROR_LOG" ADD PRIMARY KEY("OID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_FILE_PASSWORD" FROM INPUT(FILE = '/tmp/um//3_40', TYPE = 'FrontBase');
SET UNIQUE=1903 FOR "UMICH"."SM_FILE_PASSWORD";
ALTER TABLE "UMICH"."SM_FILE_PASSWORD" ADD PRIMARY KEY("FILE_PASSWORD_PKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_FOOTER" FROM INPUT(FILE = '/tmp/um//3_41', TYPE = 'FrontBase');
SET UNIQUE=3598 FOR "UMICH"."SM_FOOTER";
ALTER TABLE "UMICH"."SM_FOOTER" ADD PRIMARY KEY("WEBSITE_FKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_GROUP" FROM INPUT(FILE = '/tmp/um//3_42', TYPE = 'FrontBase');
SET UNIQUE=30571 FOR "UMICH"."SM_GROUP";
ALTER TABLE "UMICH"."SM_GROUP" ADD PRIMARY KEY("GROUP_PKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_GROUP_FILE" FROM INPUT(FILE = '/tmp/um//3_43', TYPE = 'FrontBase');
SET UNIQUE=999999 FOR "UMICH"."SM_GROUP_FILE";
ALTER TABLE "UMICH"."SM_GROUP_FILE" ADD PRIMARY KEY("GROUP_PKEY","FILE_PKEY") CACHE(500,1358,100);
INSERT INTO "UMICH"."SM_GROUP_SECTION" FROM INPUT(FILE = '/tmp/um//3_44', TYPE = 'FrontBase');
SET UNIQUE=999999 FOR "UMICH"."SM_GROUP_SECTION";
ALTER TABLE "UMICH"."SM_GROUP_SECTION" ADD PRIMARY KEY("GROUP_PKEY","SECTION_PKEY") CACHE(500,684,100);
INSERT INTO "UMICH"."SM_PAGE_COMP" FROM INPUT(FILE = '/tmp/um//3_45', TYPE = 'FrontBase');
SET UNIQUE=3627930 FOR "UMICH"."SM_PAGE_COMP";
ALTER TABLE "UMICH"."SM_PAGE_COMP" ADD PRIMARY KEY("COMPONENT_ID") CACHE(500,5762,100);
INSERT INTO "UMICH"."SM_ORG_UNIT" FROM INPUT(FILE = '/tmp/um//3_46', TYPE = 'FrontBase');
SET UNIQUE=715 FOR "UMICH"."SM_ORG_UNIT";
ALTER TABLE "UMICH"."SM_ORG_UNIT" ADD PRIMARY KEY("OID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_SECTION" FROM INPUT(FILE = '/tmp/um//3_47', TYPE = 'FrontBase');
SET UNIQUE=116131 FOR "UMICH"."SM_SECTION";
ALTER TABLE "UMICH"."SM_SECTION" ADD PRIMARY KEY("SECTION_PKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_SECTION_STYLE" FROM INPUT(FILE = '/tmp/um//3_48', TYPE = 'FrontBase');
SET UNIQUE=76 FOR "UMICH"."SM_SECTION_STYLE";
ALTER TABLE "UMICH"."SM_SECTION_STYLE" ADD PRIMARY KEY("OID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_SITE_FILE" FROM INPUT(FILE = '/tmp/um//3_49', TYPE = 'FrontBase');
SET UNIQUE=734436 FOR "UMICH"."SM_SITE_FILE";
ALTER TABLE "UMICH"."SM_SITE_FILE" ADD PRIMARY KEY("FILE_PKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_STYLE" FROM INPUT(FILE = '/tmp/um//3_50', TYPE = 'FrontBase');
SET UNIQUE=523 FOR "UMICH"."SM_STYLE";
ALTER TABLE "UMICH"."SM_STYLE" ADD PRIMARY KEY("OID") CACHE(10,1000,100);
INSERT INTO "UMICH"."SM_USAGE_LOG" FROM INPUT(FILE = '/tmp/um//3_51', TYPE = 'FrontBase');
SET UNIQUE=1455551 FOR "UMICH"."SM_USAGE_LOG";
ALTER TABLE "UMICH"."SM_USAGE_LOG" ADD PRIMARY KEY("USAGE_LOG_PKEY") CACHE(500,5121,100);
INSERT INTO "UMICH"."SM_USER" FROM INPUT(FILE = '/tmp/um//3_52', TYPE = 'FrontBase');
SET UNIQUE=100798 FOR "UMICH"."SM_USER";
ALTER TABLE "UMICH"."SM_USER" ADD PRIMARY KEY("USER_PKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_USER_GROUP" FROM INPUT(FILE = '/tmp/um//3_53', TYPE = 'FrontBase');
SET UNIQUE=999999 FOR "UMICH"."SM_USER_GROUP";
ALTER TABLE "UMICH"."SM_USER_GROUP" ADD PRIMARY KEY("GROUP_PKEY","USER_PKEY") CACHE(500,577,100);
INSERT INTO "UMICH"."SM_WEBSITE" FROM INPUT(FILE = '/tmp/um//3_54', TYPE = 'FrontBase');
SET UNIQUE=14397 FOR "UMICH"."SM_WEBSITE";
ALTER TABLE "UMICH"."SM_WEBSITE" ADD PRIMARY KEY("WEBSITE_PKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."GVC_LOOKUP" FROM INPUT(FILE = '/tmp/um//3_55', TYPE = 'FrontBase');
SET UNIQUE=110 FOR "UMICH"."GVC_LOOKUP";
ALTER TABLE "UMICH"."GVC_LOOKUP" ADD PRIMARY KEY("THE_ID") CACHE(16,158,100);
INSERT INTO "UMICH"."GVC_VA_OBJECT" FROM INPUT(FILE = '/tmp/um//3_56', TYPE = 'FrontBase');
SET UNIQUE=1 FOR "UMICH"."GVC_VA_OBJECT";
ALTER TABLE "UMICH"."GVC_VA_OBJECT" ADD PRIMARY KEY("THE_ID") CACHE(16,158,100);
INSERT INTO "UMICH"."VIRTUAL_COLUMN" FROM INPUT(FILE = '/tmp/um//3_57', TYPE = 'FrontBase');
SET UNIQUE=607311 FOR "UMICH"."VIRTUAL_COLUMN";
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" ADD PRIMARY KEY("COLUMN_ID") CACHE(500,500,100);
INSERT INTO "UMICH"."COLUMN_TYPE" FROM INPUT(FILE = '/tmp/um//3_58', TYPE = 'FrontBase');
SET UNIQUE=109 FOR "UMICH"."COLUMN_TYPE";
ALTER TABLE "UMICH"."COLUMN_TYPE" ADD PRIMARY KEY("THE_ID") CACHE(1,100,100);
INSERT INTO "UMICH"."ROOT_TABLE" FROM INPUT(FILE = '/tmp/um//3_59', TYPE = 'FrontBase');
SET UNIQUE=390770 FOR "UMICH"."ROOT_TABLE";
ALTER TABLE "UMICH"."ROOT_TABLE" ADD PRIMARY KEY("TABLE_ID") CACHE(16,158,100);
INSERT INTO "UMICH"."VIRTUAL_FIELD" FROM INPUT(FILE = '/tmp/um//3_60', TYPE = 'FrontBase');
SET UNIQUE=19716621 FOR "UMICH"."VIRTUAL_FIELD";
ALTER TABLE "UMICH"."VIRTUAL_FIELD" ADD PRIMARY KEY("VIRTUAL_FIELD_ID") CACHE(500,11875,100);
INSERT INTO "UMICH"."VIRTUAL_ROW" FROM INPUT(FILE = '/tmp/um//3_61', TYPE = 'FrontBase');
SET UNIQUE=3234223 FOR "UMICH"."VIRTUAL_ROW";
ALTER TABLE "UMICH"."VIRTUAL_ROW" ADD PRIMARY KEY("VIRTUAL_ROW_ID") CACHE(500,945,100);
INSERT INTO "UMICH"."VIRTUAL_TABLE" FROM INPUT(FILE = '/tmp/um//3_62', TYPE = 'FrontBase');
SET UNIQUE=1 FOR "UMICH"."VIRTUAL_TABLE";
ALTER TABLE "UMICH"."VIRTUAL_TABLE" ADD PRIMARY KEY("TABLE_ID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_SITE_FILE_FOLDER" FROM INPUT(FILE = '/tmp/um//3_63', TYPE = 'FrontBase');
SET UNIQUE=30124 FOR "UMICH"."SM_SITE_FILE_FOLDER";
ALTER TABLE "UMICH"."SM_SITE_FILE_FOLDER" ADD PRIMARY KEY("OID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_SECTION_TYPE" FROM INPUT(FILE = '/tmp/um//3_64', TYPE = 'FrontBase');
SET UNIQUE=7 FOR "UMICH"."SM_SECTION_TYPE";
ALTER TABLE "UMICH"."SM_SECTION_TYPE" ADD PRIMARY KEY("OID") CACHE(1,100,100);
INSERT INTO "UMICH"."SM_WEBSITE_TABLE" FROM INPUT(FILE = '/tmp/um//3_65', TYPE = 'FrontBase');
SET UNIQUE=999999 FOR "UMICH"."SM_WEBSITE_TABLE";
ALTER TABLE "UMICH"."SM_WEBSITE_TABLE" ADD PRIMARY KEY("TABLE_ID","WEBSITE_FKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_VIRTUAL_TABLE" FROM INPUT(FILE = '/tmp/um//3_66', TYPE = 'FrontBase');
SET UNIQUE=999999 FOR "UMICH"."SM_VIRTUAL_TABLE";
ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" ADD PRIMARY KEY("TABLE_ID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_LDAP_BRANCH" FROM INPUT(FILE = '/tmp/um//3_67', TYPE = 'FrontBase');
SET UNIQUE=2 FOR "UMICH"."SM_LDAP_BRANCH";
ALTER TABLE "UMICH"."SM_LDAP_BRANCH" ADD PRIMARY KEY("OID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_DA_WEBSITE_GRP_NOTIFICATION" FROM INPUT(FILE = '/tmp/um//3_68', TYPE = 'FrontBase');
SET UNIQUE=1 FOR "UMICH"."SM_DA_WEBSITE_GRP_NOTIFICATION";
ALTER TABLE "UMICH"."SM_DA_WEBSITE_GRP_NOTIFICATION" ADD PRIMARY KEY("GROUP_PKEY","COMPONENT_ID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_DA_COLUMN_NOTIFICATION" FROM INPUT(FILE = '/tmp/um//3_69', TYPE = 'FrontBase');
SET UNIQUE=1 FOR "UMICH"."SM_DA_COLUMN_NOTIFICATION";
ALTER TABLE "UMICH"."SM_DA_COLUMN_NOTIFICATION" ADD PRIMARY KEY("COMPONENT_ID","COLUMN_COMPONENT_ID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_WEBSITE_REQUEST" FROM INPUT(FILE = '/tmp/um//3_70', TYPE = 'FrontBase');
SET UNIQUE=7109 FOR "UMICH"."SM_WEBSITE_REQUEST";
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" ADD PRIMARY KEY("OID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_CHANGE_LOG" FROM INPUT(FILE = '/tmp/um//3_71', TYPE = 'FrontBase');
SET UNIQUE=13004 FOR "UMICH"."SM_CHANGE_LOG";
ALTER TABLE "UMICH"."SM_CHANGE_LOG" ADD PRIMARY KEY("OID") CACHE(16,158,100);
INSERT INTO "UMICH"."SM_WEBSITE_CHANGE_LOG" FROM INPUT(FILE = '/tmp/um//3_72', TYPE = 'FrontBase');
SET UNIQUE=1 FOR "UMICH"."SM_WEBSITE_CHANGE_LOG";
ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" ADD PRIMARY KEY("OID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_ORG_UNIT_USER" FROM INPUT(FILE = '/tmp/um//3_73', TYPE = 'FrontBase');
SET UNIQUE=999999 FOR "UMICH"."SM_ORG_UNIT_USER";
ALTER TABLE "UMICH"."SM_ORG_UNIT_USER" ADD PRIMARY KEY("ORG_UNIT_OID","USER_PKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."TASK_STATUS" FROM INPUT(FILE = '/tmp/um//3_74', TYPE = 'FrontBase');
SET UNIQUE=1000000 FOR "UMICH"."TASK_STATUS";
ALTER TABLE "UMICH"."TASK_STATUS" ADD PRIMARY KEY("THE_ID") CACHE(500,500,100);
INSERT INTO "UMICH"."TASK" FROM INPUT(FILE = '/tmp/um//3_75', TYPE = 'FrontBase');
SET UNIQUE=1005081 FOR "UMICH"."TASK";
ALTER TABLE "UMICH"."TASK" ADD PRIMARY KEY("TASK_ID") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_SECTION_CONTRIBUTOR_GROUP" FROM INPUT(FILE = '/tmp/um//3_76', TYPE = 'FrontBase');
SET UNIQUE=999999 FOR "UMICH"."SM_SECTION_CONTRIBUTOR_GROUP";
ALTER TABLE "UMICH"."SM_SECTION_CONTRIBUTOR_GROUP" ADD PRIMARY KEY("GROUP_PKEY","SECTION_PKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_SECTION_EDITOR_GROUP" FROM INPUT(FILE = '/tmp/um//3_77', TYPE = 'FrontBase');
SET UNIQUE=999999 FOR "UMICH"."SM_SECTION_EDITOR_GROUP";
ALTER TABLE "UMICH"."SM_SECTION_EDITOR_GROUP" ADD PRIMARY KEY("GROUP_PKEY","SECTION_PKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."SM_SECTION_VERSION" FROM INPUT(FILE = '/tmp/um//3_78', TYPE = 'FrontBase');
SET UNIQUE=1068298 FOR "UMICH"."SM_SECTION_VERSION";
ALTER TABLE "UMICH"."SM_SECTION_VERSION" ADD PRIMARY KEY("VERSION_PKEY") CACHE(500,500,100);
INSERT INTO "UMICH"."TASK_SECTION" FROM INPUT(FILE = '/tmp/um//3_79', TYPE = 'FrontBase');
SET UNIQUE=999999 FOR "UMICH"."TASK_SECTION";
ALTER TABLE "UMICH"."TASK_SECTION" ADD PRIMARY KEY("TASK_ID","SECTION_ID") CACHE(500,500,100);
INSERT INTO "UMICH"."TASK_TABLE" FROM INPUT(FILE = '/tmp/um//3_80', TYPE = 'FrontBase');
SET UNIQUE=999999 FOR "UMICH"."TASK_TABLE";
ALTER TABLE "UMICH"."TASK_TABLE" ADD PRIMARY KEY("TABLE_ID","TASK_ID") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_FILE_PASSWORD_SITE_FILE_FKEY" ON "UMICH"."SM_FILE_PASSWORD"("SITE_FILE_PASSWORD_FKEY") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_GROUP_PARENT_WEBSITE" ON "UMICH"."SM_GROUP"("PARENT_WEBSITE") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_GROUP_FILE_FILE_PKEY" ON "UMICH"."SM_GROUP_FILE"("FILE_PKEY") CACHE(500,776,100);
CREATE INDEX "UMICH"."SM_GROUP_SECTION_SECTION_PKEY" ON "UMICH"."SM_GROUP_SECTION"("SECTION_PKEY") CACHE(500,500,100);
CREATE INDEX "UMICH"."PAGE_COMP_PARENT" ON "UMICH"."SM_PAGE_COMP"("PARENT_ID") CACHE(500,5762,100);
CREATE INDEX "UMICH"."SM_PAGE_COMP_FILE_ID" ON "UMICH"."SM_PAGE_COMP"("RELATED_FILE_ID") CACHE(500,5762,100);
CREATE INDEX "UMICH"."SM_PAGE_COMP_FIELD_ID" ON "UMICH"."SM_PAGE_COMP"("FIELD_ID") CACHE(500,2881,100);
CREATE INDEX "UMICH"."SM_PAGE_COMP_EMBED_SECTION_FKEY" ON "UMICH"."SM_PAGE_COMP"("EMBED_SECTION_FKEY") CACHE(500,5762,100);
CREATE INDEX "UMICH"."SM_PAGE_COMP_EMBED_WEBSITE_FKEY" ON "UMICH"."SM_PAGE_COMP"("EMBED_WEBSITE_FKEY") CACHE(500,5762,100);
CREATE INDEX "UMICH"."SM_PAGE_COMP_TEMPLATE_OID" ON "UMICH"."SM_PAGE_COMP"("TEMPLATE_OID") CACHE(500,5762,100);
CREATE INDEX "UMICH"."SM_PAGE_COMP_COMPONENT_TYPE" ON "UMICH"."SM_PAGE_COMP"("COMPONENT_TYPE") CACHE(500,4322,100);
CREATE INDEX "UMICH"."SM_ORG_UNIT_OID_PARENT_ORG_UNIT" ON "UMICH"."SM_ORG_UNIT"("OID_PARENT_ORG_UNIT") CACHE(500,500,100);
CREATE INDEX "UMICH"."SECTIONS_WEBSITE" ON "UMICH"."SM_SECTION"("WEBSITE_FKEY") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_SECTION_COMPONENT_ID" ON "UMICH"."SM_SECTION"("COMPONENT_ID") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_SECTION_STYLE_OID_OWN_UNIT" ON "UMICH"."SM_SECTION_STYLE"("OID_OWN_UNIT") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_SITE_FILE_OID_SITE_FILE_FOLDER" ON "UMICH"."SM_SITE_FILE"("OID_SITE_FILE_FOLDER") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_SITE_FILE_WEBSITE_FKEY" ON "UMICH"."SM_SITE_FILE"("WEBSITE_FKEY") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_STYLE_OID_OWN_UNIT" ON "UMICH"."SM_STYLE"("OID_OWN_UNIT") CACHE(10,1000,100);
CREATE INDEX "UMICH"."SM_USER_ORG_UNIT_FOR_STYLES" ON "UMICH"."SM_USER"("ORG_UNIT_FOR_STYLES") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_USER_ID" ON "UMICH"."SM_USER"("USER_ID") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_USER_GROUP_USER_PKEY" ON "UMICH"."SM_USER_GROUP"("USER_PKEY") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_WEBSITE_OID_SECTION_STYLE" ON "UMICH"."SM_WEBSITE"("OID_SECTION_STYLE") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_WEBSITE_OID_PARENT_ORG_UNIT" ON "UMICH"."SM_WEBSITE"("OID_PARENT_ORG_UNIT") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_WEBSITE_USER_FKEY" ON "UMICH"."SM_WEBSITE"("USER_FKEY") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_WEBSITE_SITE_ID" ON "UMICH"."SM_WEBSITE"("SITE_ID") CACHE(500,500,100);
CREATE INDEX "UMICH"."VIRTUAL_COLUMN_LOOKUP_COLUMN_ID" ON "UMICH"."VIRTUAL_COLUMN"("LOOKUP_COLUMN_ID") CACHE(500,500,100);
CREATE INDEX "UMICH"."VIRTUAL_COLUMN_TABLE_ID" ON "UMICH"."VIRTUAL_COLUMN"("TABLE_ID", "COLUMN_ID") CACHE(500,500,100);
CREATE INDEX "UMICH"."VIRTUAL_FIELD_COLUMN_ID" ON "UMICH"."VIRTUAL_FIELD"("VIRTUAL_COLUMN_ID", "VIRTUAL_FIELD_ID") CACHE(500,17811,100);
CREATE INDEX "UMICH"."VIRTUAL_FIELD_VIRTUAL_ROW_ID" ON "UMICH"."VIRTUAL_FIELD"("VIRTUAL_ROW_ID", "VIRTUAL_FIELD_ID") CACHE(500,17811,100);
CREATE INDEX "UMICH"."VIRTUAL_FIELD_LOOKUP_VALUE_ID" ON "UMICH"."VIRTUAL_FIELD"("LOOKUP_VALUE_ID") CACHE(500,11875,100);
CREATE INDEX "UMICH"."VIRTUAL_FIELD_USER_FKEY" ON "UMICH"."VIRTUAL_FIELD"("USER_FKEY") CACHE(500,25600,100);
CREATE INDEX "UMICH"."VIRTUAL_ROW_VIRTUAL_TABLE_ID" ON "UMICH"."VIRTUAL_ROW"("VIRTUAL_TABLE_ID", "VIRTUAL_ROW_ID") CACHE(500,1417,100);
CREATE INDEX "UMICH"."SM_SITE_FILE_FOLDER_PARENT_FOLDER" ON "UMICH"."SM_SITE_FILE_FOLDER"("OID_PARENT_FOLDER") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_SITE_FILE_FOLDER_WEBSITE_FKEY" ON "UMICH"."SM_SITE_FILE_FOLDER"("WEBSITE_FKEY") CACHE(500,500,100);
CREATE INDEX "UMICH"."WEBSITE_TABLE_WEBSITE_FKEY" ON "UMICH"."SM_WEBSITE_TABLE"("WEBSITE_FKEY") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_DA_WEBSITE_GRP_NOTIFICATION" ON "UMICH"."SM_DA_WEBSITE_GRP_NOTIFICATION"("COMPONENT_ID") CACHE(500,500,100);
CREATE INDEX "UMICH"."SM_SECTION_VERSION_OID_COMPONENT" ON "UMICH"."SM_SECTION_VERSION"("OID_COMPONENT") CACHE(500,500,100);
CREATE INDEX "UMICH"."TASK_TABLE_TASK_ID" ON "UMICH"."TASK_TABLE"("TASK_ID") CACHE(500,500,100);
COMMIT;

SET SESSION AUTHORIZATION "UMICH";
ALTER TABLE "UMICH"."SM_DA_MODE_TEMPLATE" ADD CHECK("OID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_ERROR_LOG" ADD CHECK("OID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_FILE_PASSWORD" ADD CHECK("FILE_PASSWORD_PKEY" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_GROUP" ADD CHECK("GROUP_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_GROUP" ADD CHECK("TYPE" IS NOT NULL);
ALTER TABLE "UMICH"."SM_GROUP" ADD CHECK("CREATION_DATE" IS NOT NULL);
ALTER TABLE "UMICH"."SM_GROUP" ADD CHECK("GROUP_NAME" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_GROUP_FILE" ADD CHECK("FILE_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_GROUP_FILE" ADD CHECK("GROUP_PKEY" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_GROUP_SECTION" ADD CHECK("GROUP_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_GROUP_SECTION" ADD CHECK("SECTION_PKEY" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_PAGE_COMP" ADD CHECK("COMPONENT_ID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_PAGE_COMP" ADD CHECK("COMPONENT_TYPE" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_ORG_UNIT" ADD CHECK("IN_PUBLIC_LIST" IS NOT NULL);
ALTER TABLE "UMICH"."SM_ORG_UNIT" ADD CHECK("OID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_SECTION" ADD CHECK("SECTION_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION" ADD CHECK("TYPE_OID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION" ADD CHECK("IS_NAVIGABLE" IS NOT NULL) INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE "UMICH"."SM_SECTION" ADD CHECK("INDENTATION" IS NOT NULL) INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE "UMICH"."SM_SECTION" ADD CONSTRAINT "UMICH"."SECTION_MIME_TYPE_NOT_NULL" CHECK("MIME_TYPE" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION" ADD CONSTRAINT "UMICH"."IS_AUTO_VERSIONING_NOT_NULL" CHECK("IS_AUTO_VERSIONING" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_SECTION_STYLE" ADD CHECK("BANNER_COMP" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_STYLE" ADD CHECK("DATE_CREATED" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_STYLE" ADD CHECK("DEFAULT_STYLE" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_STYLE" ADD CHECK("FOOTER_COMP" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_STYLE" ADD CHECK("NAVBAR_COMP" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_STYLE" ADD CHECK("OID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_STYLE" ADD CHECK("PAGE_SCFLD_COMP" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_STYLE" ADD CHECK("PUBLISHED" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_STYLE" ADD CHECK("SECT_CONT_COMP" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_SITE_FILE" ADD CHECK("FILE_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SITE_FILE" ADD CHECK("OID_SITE_FILE_FOLDER" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_STYLE" ADD CHECK("DATE_CREATED" IS NOT NULL);
ALTER TABLE "UMICH"."SM_STYLE" ADD CHECK("OID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_STYLE" ADD CHECK("PUBLISHED" IS NOT NULL);
ALTER TABLE "UMICH"."SM_STYLE" ADD CHECK("NAME" IS NOT NULL) INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE "UMICH"."SM_STYLE" ADD CHECK("STYLE_ID" IS NOT NULL) INITIALLY DEFERRED DEFERRABLE;
COMMIT;

ALTER TABLE "UMICH"."SM_USAGE_LOG" ADD CHECK("USAGE_LOG_PKEY" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_USER" ADD CHECK("USER_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_USER" ADD CHECK("USER_ID" IS NOT NULL) INITIALLY DEFERRED DEFERRABLE;
COMMIT;

ALTER TABLE "UMICH"."SM_USER_GROUP" ADD CHECK("GROUP_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_USER_GROUP" ADD CHECK("USER_PKEY" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_WEBSITE" ADD CHECK("WEBSITE_PKEY" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."GVC_LOOKUP" ADD CHECK("NAME" IS NOT NULL);
ALTER TABLE "UMICH"."GVC_LOOKUP" ADD CHECK("THE_ID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."GVC_VA_OBJECT" ADD CHECK("IS_ACTIVE" IS NOT NULL);
ALTER TABLE "UMICH"."GVC_VA_OBJECT" ADD CHECK("THE_ID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."VIRTUAL_COLUMN" ADD CHECK("COLUMN_ID" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" ADD CHECK("COLUMN_TYPE_ID" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" ADD CHECK("DATE_CREATED" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" ADD CHECK("IS_SYSTEM_COLUMN" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" ADD CHECK("NAME" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" ADD CHECK("RESTRICTING_VALUE" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" ADD CHECK("TABLE_ID" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_COLUMN" ADD FOREIGN KEY("COLUMN_TYPE_ID") REFERENCES "UMICH"."COLUMN_TYPE"("THE_ID") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
COMMIT;

ALTER TABLE "UMICH"."COLUMN_TYPE" ADD CHECK("ENTITY_NAME_RESTRICTOR" IS NOT NULL);
ALTER TABLE "UMICH"."COLUMN_TYPE" ADD CHECK("NAME" IS NOT NULL);
ALTER TABLE "UMICH"."COLUMN_TYPE" ADD CHECK("THE_ID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."ROOT_TABLE" ADD CHECK("DATE_CREATED" IS NOT NULL);
ALTER TABLE "UMICH"."ROOT_TABLE" ADD CHECK("DATE_MODIFIED" IS NOT NULL);
ALTER TABLE "UMICH"."ROOT_TABLE" ADD CHECK("NAME" IS NOT NULL);
ALTER TABLE "UMICH"."ROOT_TABLE" ADD CHECK("TABLE_ID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."VIRTUAL_FIELD" ADD CHECK("RESTRICTING_VALUE" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_FIELD" ADD CHECK("VIRTUAL_COLUMN_ID" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_FIELD" ADD CHECK("VIRTUAL_FIELD_ID" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_FIELD" ADD CHECK("VIRTUAL_ROW_ID" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_FIELD" ADD FOREIGN KEY("VIRTUAL_ROW_ID") REFERENCES "UMICH"."VIRTUAL_ROW"("VIRTUAL_ROW_ID") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,11875,100);
COMMIT;

ALTER TABLE "UMICH"."VIRTUAL_ROW" ADD CHECK("VIRTUAL_ROW_ID" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_ROW" ADD CHECK("VIRTUAL_TABLE_ID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."VIRTUAL_TABLE" ADD CHECK("NAME" IS NOT NULL) INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE "UMICH"."VIRTUAL_TABLE" ADD CHECK("DATE_CREATED" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_TABLE" ADD CHECK("DATE_MODIFIED" IS NOT NULL);
ALTER TABLE "UMICH"."VIRTUAL_TABLE" ADD CHECK("TABLE_ID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_SITE_FILE_FOLDER" ADD CHECK("NAME" IS NOT NULL) INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE "UMICH"."SM_SITE_FILE_FOLDER" ADD CHECK("OID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_SECTION_TYPE" ADD CHECK("EDITOR_NAME" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_TYPE" ADD CHECK("NAME" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_TYPE" ADD CHECK("OID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_TYPE" ADD CHECK("ORDER" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_TYPE" ADD CHECK("PAGE_COMP_ENTITY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_TYPE" ADD CHECK("KEY" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_WEBSITE_TABLE" ADD CHECK("TABLE_ID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_WEBSITE_TABLE" ADD CHECK("WEBSITE_FKEY" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" ADD CHECK("NAME" IS NOT NULL) INITIALLY DEFERRED DEFERRABLE;
ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" ADD CHECK("CREATE_USER_FKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" ADD CHECK("DATE_CREATED" IS NOT NULL);
ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" ADD CHECK("DATE_MODIFIED" IS NOT NULL);
ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" ADD CHECK("TABLE_ID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_VIRTUAL_TABLE" ADD CHECK("UPDATE_USER_FKEY" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_LDAP_BRANCH" ADD CHECK("DISPLAY_NAME" IS NOT NULL);
ALTER TABLE "UMICH"."SM_LDAP_BRANCH" ADD CHECK("DISPLAY_ORDER" IS NOT NULL);
ALTER TABLE "UMICH"."SM_LDAP_BRANCH" ADD CHECK("GROUP_SUBTREE" IS NOT NULL);
ALTER TABLE "UMICH"."SM_LDAP_BRANCH" ADD CHECK("LDAP_ENTITY_NAME" IS NOT NULL);
ALTER TABLE "UMICH"."SM_LDAP_BRANCH" ADD CHECK("USER_ID_ATTR" IS NOT NULL);
ALTER TABLE "UMICH"."SM_LDAP_BRANCH" ADD CHECK("USER_SUBTREE" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_DA_WEBSITE_GRP_NOTIFICATION" ADD CHECK("GROUP_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_DA_WEBSITE_GRP_NOTIFICATION" ADD CHECK("COMPONENT_ID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_DA_COLUMN_NOTIFICATION" ADD CHECK("COMPONENT_ID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_DA_COLUMN_NOTIFICATION" ADD CHECK("COLUMN_COMPONENT_ID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" ADD CHECK("DATE_REQUESTED" IS NOT NULL);
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" ADD CHECK("OID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" ADD CHECK("ORG_UNIT_OID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" ADD CHECK("SITE_ID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" ADD CHECK("USER_FKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" ADD FOREIGN KEY("WEBSITE_FKEY") REFERENCES "UMICH"."SM_WEBSITE"("WEBSITE_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" ADD FOREIGN KEY("USER_FKEY") REFERENCES "UMICH"."SM_USER"("USER_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
ALTER TABLE "UMICH"."SM_WEBSITE_REQUEST" ADD FOREIGN KEY("ORG_UNIT_OID") REFERENCES "UMICH"."SM_ORG_UNIT"("OID") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
COMMIT;

ALTER TABLE "UMICH"."SM_CHANGE_LOG" ADD CHECK("DATE_RECORDED" IS NOT NULL);
ALTER TABLE "UMICH"."SM_CHANGE_LOG" ADD CHECK("OID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_CHANGE_LOG" ADD CHECK("USER_FKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_CHANGE_LOG" ADD FOREIGN KEY("USER_FKEY") REFERENCES "UMICH"."SM_USER"("USER_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(16,158,100);
COMMIT;

ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" ADD CHECK("DATE_RECORDED" IS NOT NULL);
ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" ADD CHECK("OID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" ADD CHECK("USER_FKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" ADD CHECK("WEBSITE_FKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" ADD FOREIGN KEY("WEBSITE_FKEY") REFERENCES "UMICH"."SM_WEBSITE"("WEBSITE_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
ALTER TABLE "UMICH"."SM_WEBSITE_CHANGE_LOG" ADD FOREIGN KEY("USER_FKEY") REFERENCES "UMICH"."SM_USER"("USER_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
COMMIT;

ALTER TABLE "UMICH"."SM_ORG_UNIT_USER" ADD CHECK("ORG_UNIT_OID" IS NOT NULL);
ALTER TABLE "UMICH"."SM_ORG_UNIT_USER" ADD CHECK("USER_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_ORG_UNIT_USER" ADD FOREIGN KEY("USER_PKEY") REFERENCES "UMICH"."SM_USER"("USER_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
ALTER TABLE "UMICH"."SM_ORG_UNIT_USER" ADD FOREIGN KEY("ORG_UNIT_OID") REFERENCES "UMICH"."SM_ORG_UNIT"("OID") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
COMMIT;

ALTER TABLE "UMICH"."TASK_STATUS" ADD CHECK("KEY" IS NOT NULL);
ALTER TABLE "UMICH"."TASK_STATUS" ADD CHECK("NAME" IS NOT NULL);
ALTER TABLE "UMICH"."TASK_STATUS" ADD CHECK("THE_ID" IS NOT NULL);
COMMIT;

ALTER TABLE "UMICH"."TASK" ADD CHECK("CREATED_DATE" IS NOT NULL);
ALTER TABLE "UMICH"."TASK" ADD CHECK("STATUS_ID" IS NOT NULL);
ALTER TABLE "UMICH"."TASK" ADD CHECK("TASK_ID" IS NOT NULL);
ALTER TABLE "UMICH"."TASK" ADD CHECK("TASK_TYPE" IS NOT NULL);
ALTER TABLE "UMICH"."TASK" ADD CHECK("USER_ID" IS NOT NULL);
ALTER TABLE "UMICH"."TASK" ADD FOREIGN KEY("STATUS_ID") REFERENCES "UMICH"."TASK_STATUS"("THE_ID") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
ALTER TABLE "UMICH"."TASK" ADD FOREIGN KEY("SOURCE_SECTION_ID") REFERENCES "UMICH"."SM_SECTION"("SECTION_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
ALTER TABLE "UMICH"."TASK" ADD FOREIGN KEY("RELATED_SECTION_ID") REFERENCES "UMICH"."SM_SECTION"("SECTION_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
ALTER TABLE "UMICH"."TASK" ADD FOREIGN KEY("RELATED_SITE_FILE_FOLDER_ID") REFERENCES "UMICH"."SM_SITE_FILE_FOLDER"("OID") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
ALTER TABLE "UMICH"."TASK" ADD FOREIGN KEY("RELATED_SITE_FILE_ID") REFERENCES "UMICH"."SM_SITE_FILE"("FILE_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
ALTER TABLE "UMICH"."TASK" ADD FOREIGN KEY("ORG_UNIT_ID") REFERENCES "UMICH"."SM_ORG_UNIT"("OID") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
COMMIT;

ALTER TABLE "UMICH"."SM_SECTION_CONTRIBUTOR_GROUP" ADD CHECK("GROUP_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_CONTRIBUTOR_GROUP" ADD CHECK("SECTION_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_CONTRIBUTOR_GROUP" ADD FOREIGN KEY("SECTION_PKEY") REFERENCES "UMICH"."SM_SECTION"("SECTION_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
COMMIT;

ALTER TABLE "UMICH"."SM_SECTION_EDITOR_GROUP" ADD CHECK("GROUP_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_EDITOR_GROUP" ADD CHECK("SECTION_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_EDITOR_GROUP" ADD FOREIGN KEY("SECTION_PKEY") REFERENCES "UMICH"."SM_SECTION"("SECTION_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
COMMIT;

ALTER TABLE "UMICH"."SM_SECTION_VERSION" ADD CHECK("IS_LOCKED" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_VERSION" ADD CHECK("NAME" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_VERSION" ADD CHECK("OID_COMPONENT" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_VERSION" ADD CHECK("OID_CREATED_BY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_VERSION" ADD CHECK("OID_SECTION" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_VERSION" ADD CHECK("VERSION_NUMBER" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_VERSION" ADD CHECK("VERSION_PKEY" IS NOT NULL);
ALTER TABLE "UMICH"."SM_SECTION_VERSION" ADD FOREIGN KEY("OID_SECTION") REFERENCES "UMICH"."SM_SECTION"("SECTION_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
COMMIT;

ALTER TABLE "UMICH"."TASK_SECTION" ADD CHECK("TASK_ID" IS NOT NULL);
ALTER TABLE "UMICH"."TASK_SECTION" ADD CHECK("SECTION_ID" IS NOT NULL);
ALTER TABLE "UMICH"."TASK_SECTION" ADD FOREIGN KEY("SECTION_ID") REFERENCES "UMICH"."SM_SECTION"("SECTION_PKEY") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
COMMIT;

ALTER TABLE "UMICH"."TASK_TABLE" ADD CHECK("TABLE_ID" IS NOT NULL);
ALTER TABLE "UMICH"."TASK_TABLE" ADD CHECK("TASK_ID" IS NOT NULL);
ALTER TABLE "UMICH"."TASK_TABLE" ADD FOREIGN KEY("TABLE_ID") REFERENCES "UMICH"."SM_VIRTUAL_TABLE"("TABLE_ID") ON UPDATE NO ACTION ON DELETE NO ACTION INITIALLY DEFERRED DEFERRABLE CACHE(500,500,100);
COMMIT;

SET SESSION AUTHORIZATION "UMICH";
ALTER USER "UMICH" SET PASSWD '7ef3f5d94d3d6c6c';
COMMIT;
SET SESSION AUTHORIZATION "_PUBLIC";
ALTER USER "_PUBLIC" SET PASSWD '06a017a165b0368e';
COMMIT;
SET SESSION AUTHORIZATION "_SYSTEM";
ALTER USER "_SYSTEM" SET PASSWD '3243981c1687728c';
COMMIT;
SET DATABASE TRANSACTION 5274922;
COMMIT;
