/* Generated By:JJTree: Do not edit this line. JassMethodBodyBlock.java */

package jass.parser;

public class JassMethodBodyBlock extends SimpleNode {
  public JassMethodBodyBlock(int id) {
    super(id);
  }

  public JassMethodBodyBlock(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
