/* Generated By:JJTree: Do not edit this line. JassInitializer.java */

package jass.parser;

public class JassInitializer extends SimpleNode {
  public JassInitializer(int id) {
    super(id);
  }

  public JassInitializer(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
