/* Generated By:JJTree: Do not edit this line. JassFieldReference.java */

package jass.parser;

public class JassFieldReference extends SimpleNode {
  public JassFieldReference(int id) {
    super(id);
  }

  public JassFieldReference(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
