/* Generated By:JJTree: Do not edit this line. JassRetryStatement.java */

package jass.parser;

public class JassRetryStatement extends SimpleNode {
  public JassRetryStatement(int id) {
    super(id);
  }

  public JassRetryStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
