/* Generated By:JJTree: Do not edit this line. JassAssertionExpression.java */

package jass.parser;

public class JassAssertionExpression extends SimpleNode {
  public JassAssertionExpression(int id) {
    super(id);
  }

  public JassAssertionExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
