/* Generated By:JJTree: Do not edit this line. JassRescueCatch.java */

package jass.parser;

public class JassRescueCatch extends SimpleNode {
  public JassRescueCatch(int id) {
    super(id);
  }

  public JassRescueCatch(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
