/* Generated By:JJTree: Do not edit this line. JassEqualityExpression.java */

package jass.parser;

public class JassEqualityExpression extends SimpleNode {
  public JassEqualityExpression(int id) {
    super(id);
  }

  public JassEqualityExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
