/* Generated By:JJTree: Do not edit this line. JassNullLiteral.java */

package jass.parser;

public class JassNullLiteral extends SimpleNode {
  public JassNullLiteral(int id) {
    super(id);
  }

  public JassNullLiteral(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
