/* Generated By:JJTree: Do not edit this line. JassAssertionConditionalExpression.java */

package jass.parser;

public class JassAssertionConditionalExpression extends SimpleNode {
  public JassAssertionConditionalExpression(int id) {
    super(id);
  }

  public JassAssertionConditionalExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
