/* Generated By:JJTree: Do not edit this line. JassArrayInitializer.java */

package jass.parser;

public class JassArrayInitializer extends SimpleNode {
  public JassArrayInitializer(int id) {
    super(id);
  }

  public JassArrayInitializer(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
