/* Generated By:JJTree: Do not edit this line. JassAssertionArgumentList.java */

package jass.parser;

public class JassAssertionArgumentList extends SimpleNode {
  public JassAssertionArgumentList(int id) {
    super(id);
  }

  public JassAssertionArgumentList(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
