/* Generated By:JJTree: Do not edit this line. JassPreIncrementExpression.java */

package jass.parser;

public class JassPreIncrementExpression extends SimpleNode {
  public JassPreIncrementExpression(int id) {
    super(id);
  }

  public JassPreIncrementExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
