/* Generated By:JJTree: Do not edit this line. JassMethodDeclaration.java */

package jass.parser;

public class JassMethodDeclaration extends SimpleNode {
  public JassMethodDeclaration(int id) {
    super(id);
  }

  public JassMethodDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
