/* Generated By:JJTree: Do not edit this line. JassAssertionClause.java */

package jass.parser;

public class JassAssertionClause extends SimpleNode {
  public JassAssertionClause(int id) {
    super(id);
  }

  public JassAssertionClause(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
