/* Generated By:JJTree: Do not edit this line. JassInvariantClause.java */

package jass.parser;

public class JassInvariantClause extends SimpleNode {
  public JassInvariantClause(int id) {
    super(id);
  }

  public JassInvariantClause(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
