/* Generated By:JJTree: Do not edit this line. JassBasicProcess.java */

package jass.parser;

public class JassBasicProcess extends SimpleNode {
  public JassBasicProcess(int id) {
    super(id);
  }

  public JassBasicProcess(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
