/* Generated By:JJTree: Do not edit this line. JassProcessParallelExpression.java */

package jass.parser;

public class JassProcessParallelExpression extends SimpleNode {
  public JassProcessParallelExpression(int id) {
    super(id);
  }

  public JassProcessParallelExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
