/* Generated By:JJTree: Do not edit this line. JassBooleanLiteral.java */

package jass.parser;

public class JassBooleanLiteral extends SimpleNode {
  public JassBooleanLiteral(int id) {
    super(id);
  }

  public JassBooleanLiteral(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
