/* Generated By:JJTree: Do not edit this line. JassBlockStatement.java */

package jass.parser;

public class JassBlockStatement extends SimpleNode {
  public JassBlockStatement(int id) {
    super(id);
  }

  public JassBlockStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
