/* Generated By:JJTree: Do not edit this line. JassPostfixOperator.java */

package jass.parser;

public class JassPostfixOperator extends SimpleNode {
  public JassPostfixOperator(int id) {
    super(id);
  }

  public JassPostfixOperator(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
