/* Generated By:JJTree: Do not edit this line. JassBlock.java */

package jass.parser;

public class JassBlock extends SimpleNode {
  public JassBlock(int id) {
    super(id);
  }

  public JassBlock(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
