/* Generated By:JJTree: Do not edit this line. JassTraceAssertion.java */

package jass.parser;

public class JassTraceAssertion extends SimpleNode {
  public JassTraceAssertion(int id) {
    super(id);
  }

  public JassTraceAssertion(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
