/* Generated By:JJTree: Do not edit this line. JassInterfaceMemberDeclaration.java */

package jass.parser;

public class JassInterfaceMemberDeclaration extends SimpleNode {
  public JassInterfaceMemberDeclaration(int id) {
    super(id);
  }

  public JassInterfaceMemberDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
