/* Generated By:JJTree: Do not edit this line. JassAssertionUnaryExpressionNotPlusMinus.java */

package jass.parser;

public class JassAssertionUnaryExpressionNotPlusMinus extends SimpleNode {
  public JassAssertionUnaryExpressionNotPlusMinus(int id) {
    super(id);
  }

  public JassAssertionUnaryExpressionNotPlusMinus(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
