/* Generated By:JJTree: Do not edit this line. JassCommunicationParameter.java */

package jass.parser;

public class JassCommunicationParameter extends SimpleNode {
  public JassCommunicationParameter(int id) {
    super(id);
  }

  public JassCommunicationParameter(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
