/* Generated By:JJTree: Do not edit this line. JassUnmodifiedInterfaceDeclaration.java */

package jass.parser;

public class JassUnmodifiedInterfaceDeclaration extends SimpleNode {
  public JassUnmodifiedInterfaceDeclaration(int id) {
    super(id);
  }

  public JassUnmodifiedInterfaceDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
