/* Generated By:JJTree: Do not edit this line. JassLayedDownParameter.java */

package jass.parser;

public class JassLayedDownParameter extends SimpleNode {
  public JassLayedDownParameter(int id) {
    super(id);
  }

  public JassLayedDownParameter(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
