/* Generated By:JJTree: Do not edit this line. JassPreDecrementExpression.java */

package jass.parser;

public class JassPreDecrementExpression extends SimpleNode {
  public JassPreDecrementExpression(int id) {
    super(id);
  }

  public JassPreDecrementExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
