/* Generated By:JJTree: Do not edit this line. JassAssertionFiniteEnumerationCreation.java */

package jass.parser;

public class JassAssertionFiniteEnumerationCreation extends SimpleNode {
  public JassAssertionFiniteEnumerationCreation(int id) {
    super(id);
  }

  public JassAssertionFiniteEnumerationCreation(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
