/* Generated By:JJTree: Do not edit this line. JassInvariantAssertion.java */

package jass.parser;

public class JassInvariantAssertion extends SimpleNode {
  public JassInvariantAssertion(int id) {
    super(id);
  }

  public JassInvariantAssertion(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
