/* Generated By:JJTree: Do not edit this line. JassProcessDeclarator.java */

package jass.parser;

public class JassProcessDeclarator extends SimpleNode {
  public JassProcessDeclarator(int id) {
    super(id);
  }

  public JassProcessDeclarator(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
