/* Generated By:JJTree: Do not edit this line. JassCommunicationParameterList.java */

package jass.parser;

public class JassCommunicationParameterList extends SimpleNode {
  public JassCommunicationParameterList(int id) {
    super(id);
  }

  public JassCommunicationParameterList(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
