/* Generated By:JJTree: Do not edit this line. JassCastExpression.java */

package jass.parser;

public class JassCastExpression extends SimpleNode {
  public JassCastExpression(int id) {
    super(id);
  }

  public JassCastExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
