/* Generated By:JJTree: Do not edit this line. JassAssertionPrimaryExpression.java */

package jass.parser;

public class JassAssertionPrimaryExpression extends SimpleNode {
  public JassAssertionPrimaryExpression(int id) {
    super(id);
  }

  public JassAssertionPrimaryExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
