/* Generated By:JJTree: Do not edit this line. JassInterfaceDeclaration.java */

package jass.parser;

public class JassInterfaceDeclaration extends SimpleNode {
  public JassInterfaceDeclaration(int id) {
    super(id);
  }

  public JassInterfaceDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
