/* Generated By:JJTree: Do not edit this line. JassAssertionCastExpression.java */

package jass.parser;

public class JassAssertionCastExpression extends SimpleNode {
  public JassAssertionCastExpression(int id) {
    super(id);
  }

  public JassAssertionCastExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
