/* Generated By:JJTree: Do not edit this line. JassCommunicationExpressions.java */

package jass.parser;

public class JassCommunicationExpressions extends SimpleNode {
  public JassCommunicationExpressions(int id) {
    super(id);
  }

  public JassCommunicationExpressions(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
