/* Generated By:JJTree: Do not edit this line. JassExpression.java */

package jass.parser;

public class JassExpression extends SimpleNode {
  public JassExpression(int id) {
    super(id);
  }

  public JassExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
