/* Generated By:JJTree: Do not edit this line. JassProcessChoiceExpression.java */

package jass.parser;

public class JassProcessChoiceExpression extends SimpleNode {
  public JassProcessChoiceExpression(int id) {
    super(id);
  }

  public JassProcessChoiceExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
