/* Generated By:JJTree: Do not edit this line. JassInstanceOfExpression.java */

package jass.parser;

public class JassInstanceOfExpression extends SimpleNode {
  public JassInstanceOfExpression(int id) {
    super(id);
  }

  public JassInstanceOfExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
