/* Generated By:JJTree: Do not edit this line. JassSwitchLabel.java */

package jass.parser;

public class JassSwitchLabel extends SimpleNode {
  public JassSwitchLabel(int id) {
    super(id);
  }

  public JassSwitchLabel(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
