/* Generated By:JJTree: Do not edit this line. JassPrimarySuffix.java */

package jass.parser;

public class JassPrimarySuffix extends SimpleNode {
  public JassPrimarySuffix(int id) {
    super(id);
  }

  public JassPrimarySuffix(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
