/* Generated By:JJTree: Do not edit this line. JassDoStatement.java */

package jass.parser;

public class JassDoStatement extends SimpleNode {
  public JassDoStatement(int id) {
    super(id);
  }

  public JassDoStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
