/* Generated By:JJTree: Do not edit this line. JassUnmodifiedClassDeclaration.java */

package jass.parser;

public class JassUnmodifiedClassDeclaration extends SimpleNode {
  public JassUnmodifiedClassDeclaration(int id) {
    super(id);
  }

  public JassUnmodifiedClassDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
