/* Generated By:JJTree: Do not edit this line. JassLocalVariableDeclaration.java */

package jass.parser;

public class JassLocalVariableDeclaration extends SimpleNode {
  public JassLocalVariableDeclaration(int id) {
    super(id);
  }

  public JassLocalVariableDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
