/* Generated By:JJTree: Do not edit this line. JassMultiplicativeExpression.java */

package jass.parser;

public class JassMultiplicativeExpression extends SimpleNode {
  public JassMultiplicativeExpression(int id) {
    super(id);
  }

  public JassMultiplicativeExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
