/* Generated By:JJTree: Do not edit this line. JassClassInvariantClause.java */

package jass.parser;

public class JassClassInvariantClause extends SimpleNode {
  public JassClassInvariantClause(int id) {
    super(id);
  }

  public JassClassInvariantClause(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
