/* Generated By:JJTree: Do not edit this line. JassFieldDeclaration.java */

package jass.parser;

public class JassFieldDeclaration extends SimpleNode {
  public JassFieldDeclaration(int id) {
    super(id);
  }

  public JassFieldDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
