/* Generated By:JJTree: Do not edit this line. JassRelationalExpression.java */

package jass.parser;

public class JassRelationalExpression extends SimpleNode {
  public JassRelationalExpression(int id) {
    super(id);
  }

  public JassRelationalExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
