/* Generated By:JJTree: Do not edit this line. JassAssertionInstanceOfExpression.java */

package jass.parser;

public class JassAssertionInstanceOfExpression extends SimpleNode {
  public JassAssertionInstanceOfExpression(int id) {
    super(id);
  }

  public JassAssertionInstanceOfExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
