/* Generated By:JJTree: Do not edit this line. JassType.java */

package jass.parser;

public class JassType extends SimpleNode {
  public JassType(int id) {
    super(id);
  }

  public JassType(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
