/* Generated By:JJTree: Do not edit this line. JassCommunicationWithWildcards.java */

package jass.parser;

public class JassCommunicationWithWildcards extends SimpleNode {
  public JassCommunicationWithWildcards(int id) {
    super(id);
  }

  public JassCommunicationWithWildcards(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
