/* Generated By:JJTree: Do not edit this line. JassAssertionArguments.java */

package jass.parser;

public class JassAssertionArguments extends SimpleNode {
  public JassAssertionArguments(int id) {
    super(id);
  }

  public JassAssertionArguments(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
