/* Generated By:JJTree: Do not edit this line. JassAssertionMultiplicativeExpression.java */

package jass.parser;

public class JassAssertionMultiplicativeExpression extends SimpleNode {
  public JassAssertionMultiplicativeExpression(int id) {
    super(id);
  }

  public JassAssertionMultiplicativeExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
