/* Generated By:JJTree: Do not edit this line. JassResultType.java */

package jass.parser;

public class JassResultType extends SimpleNode {
  public JassResultType(int id) {
    super(id);
  }

  public JassResultType(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
