/* Generated By:JJTree: Do not edit this line. JassPrimaryExpression.java */

package jass.parser;

public class JassPrimaryExpression extends SimpleNode {
  public JassPrimaryExpression(int id) {
    super(id);
  }

  public JassPrimaryExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
