--
-- FrontBase script for GVCEOFValidation specific needs
--
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

CREATE TABLE "NOTIFYING_EDITING_CONTEXT_TEST_OBJECT" (
	"ID" INTEGER NOT NULL,
	"RELATED_ID" INTEGER,
	"STRING_VALUE" VARCHAR(50)
);

SET UNIQUE = 1000000 FOR "NOTIFYING_EDITING_CONTEXT_TEST_OBJECT";

ALTER TABLE "NOTIFYING_EDITING_CONTEXT_TEST_OBJECT" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "NOTIFYING_EDITING_CONTEXT_TEST_OBJECT" ADD FOREIGN KEY ("RELATED_ID") REFERENCES "NOTIFYING_EDITING_CONTEXT_TEST_OBJECT" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE entity_with_constraints ADD CONSTRAINT quantity_below_10 CHECK (quantity < 10);

COMMIT;

