SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

CREATE TABLE "GVC_LOCALE" (
	"name" VARCHAR(50) NOT NULL,
	"the_id" INTEGER NOT NULL
);

CREATE TABLE "GVC_LOOKUP" (
	"name" VARCHAR(50) NOT NULL,
	"the_id" INTEGER NOT NULL
);

CREATE TABLE "GVC_LOOKUP_LOCALIZATION" (
	"LOCALE_ID" INTEGER NOT NULL,
	"LOCALIZED_NAME" VARCHAR(50) NOT NULL,
	"LOOKUP_ID" INTEGER NOT NULL
);

CREATE TABLE "GVC_VA_OBJECT" (
	"is_active" CHARACTER(1) NOT NULL,
	"the_id" INTEGER NOT NULL
);

SET UNIQUE = 1000000 FOR "GVC_LOOKUP";

SET UNIQUE = 1000000 FOR "GVC_LOCALE";

SET UNIQUE = 1000000 FOR "GVC_VA_OBJECT";

ALTER TABLE "GVC_LOCALE" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GVC_LOOKUP" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GVC_LOOKUP_LOCALIZATION" ADD PRIMARY KEY ("LOCALE_ID","LOOKUP_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GVC_VA_OBJECT" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "GVC_LOOKUP_LOCALIZATION" ADD FOREIGN KEY ("LOCALE_ID") REFERENCES "GVC_LOCALE" ("THE_ID") DEFERRABLE INITIALLY DEFERRED;

COMMIT;

