SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, LOCKING PESSIMISTIC;

-- The 'Create Database' option is unavailable.;

CREATE TABLE "test_archivable_keyed_lookup" (
	"is_active" CHARACTER(1) NOT NULL,
	"key" VARCHAR(50) NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"the_id" INTEGER NOT NULL
);

CREATE TABLE "test_archivable_lookup" (
	"is_active" CHARACTER(1) NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"the_id" INTEGER NOT NULL
);

CREATE TABLE "test_keyed_lookup" (
	"key" VARCHAR(50) NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"the_id" INTEGER NOT NULL
);

CREATE TABLE "TEST_LOOKUP" (
	"name" VARCHAR(50) NOT NULL,
	"the_id" INTEGER NOT NULL
);

CREATE TABLE "TEST_ORDERED_LOOKUP" (
	"name" VARCHAR(50) NOT NULL,
	"ORDERING" INTEGER NOT NULL,
	"the_id" INTEGER NOT NULL
);

CREATE TABLE "test_ver_arch_lookup" (
	"is_active" CHARACTER(1) NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"the_id" INTEGER NOT NULL
);

CREATE TABLE "TEST_VERSIONED_OBJECT" (
	"is_active" CHARACTER(1) NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"the_id" INTEGER NOT NULL
);

SET UNIQUE = 1000000 FOR "TEST_VERSIONED_OBJECT";

SET UNIQUE = 1000000 FOR "test_ver_arch_lookup";

SET UNIQUE = 1000000 FOR "test_archivable_lookup";

SET UNIQUE = 1000000 FOR "test_archivable_keyed_lookup";

SET UNIQUE = 1000000 FOR "TEST_ORDERED_LOOKUP";

SET UNIQUE = 1000000 FOR "TEST_LOOKUP";

SET UNIQUE = 1000000 FOR "test_keyed_lookup";

ALTER TABLE "TEST_ARCHIVABLE_KEYED_LOOKUP" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEST_ARCHIVABLE_LOOKUP" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEST_KEYED_LOOKUP" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEST_LOOKUP" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEST_ORDERED_LOOKUP" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEST_VER_ARCH_LOOKUP" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEST_VERSIONED_OBJECT" ADD PRIMARY KEY ("THE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

COMMIT;

