/* Generated By:JJTree: Do not edit this line. JassVariantClause.java */

package jass.parser;

public class JassVariantClause extends SimpleNode {
  public JassVariantClause(int id) {
    super(id);
  }

  public JassVariantClause(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
