/* Generated By:JJTree: Do not edit this line. JassTraceConstant.java */

package jass.parser;

public class JassTraceConstant extends SimpleNode {
  public JassTraceConstant(int id) {
    super(id);
  }

  public JassTraceConstant(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
