/* Generated By:JJTree: Do not edit this line. JassProcessJavaBlock.java */

package jass.parser;

public class JassProcessJavaBlock extends SimpleNode {
  public JassProcessJavaBlock(int id) {
    super(id);
  }

  public JassProcessJavaBlock(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
