/* Generated By:JJTree: Do not edit this line. JassClassDeclaration.java */

package jass.parser;

public class JassClassDeclaration extends SimpleNode {
  public JassClassDeclaration(int id) {
    super(id);
  }

  public JassClassDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
