/* Generated By:JJTree: Do not edit this line. JassConditionalOrExpression.java */

package jass.parser;

public class JassConditionalOrExpression extends SimpleNode {
  public JassConditionalOrExpression(int id) {
    super(id);
  }

  public JassConditionalOrExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
