/* Generated By:JJTree: Do not edit this line. JassEnsureClause.java */

package jass.parser;

public class JassEnsureClause extends SimpleNode {
  public JassEnsureClause(int id) {
    super(id);
  }

  public JassEnsureClause(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
