/* Generated By:JJTree: Do not edit this line. JassProcessIfElseExpression.java */

package jass.parser;

public class JassProcessIfElseExpression extends SimpleNode {
  public JassProcessIfElseExpression(int id) {
    super(id);
  }

  public JassProcessIfElseExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
