/* Generated By:JJTree: Do not edit this line. JassUnaryExpression.java */

package jass.parser;

public class JassUnaryExpression extends SimpleNode {
  public JassUnaryExpression(int id) {
    super(id);
  }

  public JassUnaryExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
