/* Generated By:JJTree: Do not edit this line. JassTryStatement.java */

package jass.parser;

public class JassTryStatement extends SimpleNode {
  public JassTryStatement(int id) {
    super(id);
  }

  public JassTryStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
