/* Generated By:JJTree: Do not edit this line. JassVariableDeclaratorId.java */

package jass.parser;

public class JassVariableDeclaratorId extends SimpleNode {
  public JassVariableDeclaratorId(int id) {
    super(id);
  }

  public JassVariableDeclaratorId(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
