/* Generated By:JJTree: Do not edit this line. JassConditionalCommunication.java */

package jass.parser;

public class JassConditionalCommunication extends SimpleNode {
  public JassConditionalCommunication(int id) {
    super(id);
  }

  public JassConditionalCommunication(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
