/* Generated By:JJTree: Do not edit this line. JassSwitchStatement.java */

package jass.parser;

public class JassSwitchStatement extends SimpleNode {
  public JassSwitchStatement(int id) {
    super(id);
  }

  public JassSwitchStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
