/* Generated By:JJTree: Do not edit this line. JassTypedParameter.java */

package jass.parser;

public class JassTypedParameter extends SimpleNode {
  public JassTypedParameter(int id) {
    super(id);
  }

  public JassTypedParameter(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
