/* Generated By:JJTree: Do not edit this line. JassMethodDeclarationLookahead.java */

package jass.parser;

public class JassMethodDeclarationLookahead extends SimpleNode {
  public JassMethodDeclarationLookahead(int id) {
    super(id);
  }

  public JassMethodDeclarationLookahead(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
