/* Generated By:JJTree: Do not edit this line. JassOutputParameter.java */

package jass.parser;

public class JassOutputParameter extends SimpleNode {
  public JassOutputParameter(int id) {
    super(id);
  }

  public JassOutputParameter(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
