/* Generated By:JJTree: Do not edit this line. JassAssertionUnaryExpression.java */

package jass.parser;

public class JassAssertionUnaryExpression extends SimpleNode {
  public JassAssertionUnaryExpression(int id) {
    super(id);
  }

  public JassAssertionUnaryExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
