/* Generated By:JJTree: Do not edit this line. JassProcessCall.java */

package jass.parser;

public class JassProcessCall extends SimpleNode {
  public JassProcessCall(int id) {
    super(id);
  }

  public JassProcessCall(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
