/* Generated By:JJTree: Do not edit this line. JassTraceAssertionDeclaration.java */

package jass.parser;

public class JassTraceAssertionDeclaration extends SimpleNode {
  public JassTraceAssertionDeclaration(int id) {
    super(id);
  }

  public JassTraceAssertionDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
