/* Generated By:JJTree: Do not edit this line. JassAssertionRelationalExpression.java */

package jass.parser;

public class JassAssertionRelationalExpression extends SimpleNode {
  public JassAssertionRelationalExpression(int id) {
    super(id);
  }

  public JassAssertionRelationalExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
