/* Generated By:JJTree: Do not edit this line. JassAssertionConditionalOrExpression.java */

package jass.parser;

public class JassAssertionConditionalOrExpression extends SimpleNode {
  public JassAssertionConditionalOrExpression(int id) {
    super(id);
  }

  public JassAssertionConditionalOrExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
