/* Generated By:JJTree: Do not edit this line. JassInputParameter.java */

package jass.parser;

public class JassInputParameter extends SimpleNode {
  public JassInputParameter(int id) {
    super(id);
  }

  public JassInputParameter(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
