/* Generated By:JJTree: Do not edit this line. JassStatement.java */

package jass.parser;

public class JassStatement extends SimpleNode {
  public JassStatement(int id) {
    super(id);
  }

  public JassStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
