/* Generated By:JJTree: Do not edit this line. JassAssertionPrimarySuffix.java */

package jass.parser;

public class JassAssertionPrimarySuffix extends SimpleNode {
  public JassAssertionPrimarySuffix(int id) {
    super(id);
  }

  public JassAssertionPrimarySuffix(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
