/* Generated By:JJTree: Do not edit this line. JassClassBodyDeclaration.java */

package jass.parser;

public class JassClassBodyDeclaration extends SimpleNode {
  public JassClassBodyDeclaration(int id) {
    super(id);
  }

  public JassClassBodyDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
