/* Generated By:JJTree: Do not edit this line. JassCompilationUnit.java */

package jass.parser;

public class JassCompilationUnit extends SimpleNode {
  public JassCompilationUnit(int id) {
    super(id);
  }

  public JassCompilationUnit(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
