/* Generated By:JJTree: Do not edit this line. JassBooleanChangeAssertion.java */

package jass.parser;

public class JassBooleanChangeAssertion extends SimpleNode {
  public JassBooleanChangeAssertion(int id) {
    super(id);
  }

  public JassBooleanChangeAssertion(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
