/* Generated By:JJTree: Do not edit this line. JassUnaryExpressionNotPlusMinus.java */

package jass.parser;

public class JassUnaryExpressionNotPlusMinus extends SimpleNode {
  public JassUnaryExpressionNotPlusMinus(int id) {
    super(id);
  }

  public JassUnaryExpressionNotPlusMinus(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
