/* Generated By:JJTree: Do not edit this line. JassUnaryPlusMinusOperator.java */

package jass.parser;

public class JassUnaryPlusMinusOperator extends SimpleNode {
  public JassUnaryPlusMinusOperator(int id) {
    super(id);
  }

  public JassUnaryPlusMinusOperator(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
