/* Generated By:JJTree: Do not edit this line. JassIfStatement.java */

package jass.parser;

public class JassIfStatement extends SimpleNode {
  public JassIfStatement(int id) {
    super(id);
  }

  public JassIfStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
