/* Generated By:JJTree: Do not edit this line. JassThrowStatement.java */

package jass.parser;

public class JassThrowStatement extends SimpleNode {
  public JassThrowStatement(int id) {
    super(id);
  }

  public JassThrowStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
