/* Generated By:JJTree: Do not edit this line. JassUnaryNotPlusMinusOperator.java */

package jass.parser;

public class JassUnaryNotPlusMinusOperator extends SimpleNode {
  public JassUnaryNotPlusMinusOperator(int id) {
    super(id);
  }

  public JassUnaryNotPlusMinusOperator(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
