/* Generated By:JJTree: Do not edit this line. JassProcessExpression.java */

package jass.parser;

public class JassProcessExpression extends SimpleNode {
  public JassProcessExpression(int id) {
    super(id);
  }

  public JassProcessExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
