/* Generated By:JJTree: Do not edit this line. JassAssertionEqualityExpression.java */

package jass.parser;

public class JassAssertionEqualityExpression extends SimpleNode {
  public JassAssertionEqualityExpression(int id) {
    super(id);
  }

  public JassAssertionEqualityExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
