/* Generated By:JJTree: Do not edit this line. JassFormalParameter.java */

package jass.parser;

public class JassFormalParameter extends SimpleNode {
  public JassFormalParameter(int id) {
    super(id);
  }

  public JassFormalParameter(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
