/* Generated By:JJTree: Do not edit this line. JassConstructorDeclaration.java */

package jass.parser;

public class JassConstructorDeclaration extends SimpleNode {
  public JassConstructorDeclaration(int id) {
    super(id);
  }

  public JassConstructorDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
