/* Generated By:JJTree: Do not edit this line. JassCommunicationExpression.java */

package jass.parser;

public class JassCommunicationExpression extends SimpleNode {
  public JassCommunicationExpression(int id) {
    super(id);
  }

  public JassCommunicationExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
