/* Generated By:JJTree: Do not edit this line. JassRequireClause.java */

package jass.parser;

public class JassRequireClause extends SimpleNode {
  public JassRequireClause(int id) {
    super(id);
  }

  public JassRequireClause(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
