/* Generated By:JJTree: Do not edit this line. JassAssertionShiftExpression.java */

package jass.parser;

public class JassAssertionShiftExpression extends SimpleNode {
  public JassAssertionShiftExpression(int id) {
    super(id);
  }

  public JassAssertionShiftExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
