/* Generated By:JJTree: Do not edit this line. JassImportDeclaration.java */

package jass.parser;

public class JassImportDeclaration extends SimpleNode {
  public JassImportDeclaration(int id) {
    super(id);
  }

  public JassImportDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
