/* Generated By:JJTree: Do not edit this line. JassProcessPrefixExpression.java */

package jass.parser;

public class JassProcessPrefixExpression extends SimpleNode {
  public JassProcessPrefixExpression(int id) {
    super(id);
  }

  public JassProcessPrefixExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
