/* Generated By:JJTree: Do not edit this line. JassArguments.java */

package jass.parser;

public class JassArguments extends SimpleNode {
  public JassArguments(int id) {
    super(id);
  }

  public JassArguments(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
