/* Generated By:JJTree: Do not edit this line. JassPrimaryPrefix.java */

package jass.parser;

public class JassPrimaryPrefix extends SimpleNode {
  public JassPrimaryPrefix(int id) {
    super(id);
  }

  public JassPrimaryPrefix(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
