/* Generated By:JJTree: Do not edit this line. JassVariableDeclarator.java */

package jass.parser;

public class JassVariableDeclarator extends SimpleNode {
  public JassVariableDeclarator(int id) {
    super(id);
  }

  public JassVariableDeclarator(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
