/* Generated By:JJTree: Do not edit this line. JassAllocationExpression.java */

package jass.parser;

public class JassAllocationExpression extends SimpleNode {
  public JassAllocationExpression(int id) {
    super(id);
  }

  public JassAllocationExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
