/* Generated By:JJTree: Do not edit this line. JassName.java */

package jass.parser;

public class JassName extends SimpleNode {
  public JassName(int id) {
    super(id);
  }

  public JassName(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
