/* Generated By:JJTree: Do not edit this line. JassNestedClassDeclaration.java */

package jass.parser;

public class JassNestedClassDeclaration extends SimpleNode {
  public JassNestedClassDeclaration(int id) {
    super(id);
  }

  public JassNestedClassDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
