/* Generated By:JJTree: Do not edit this line. JassAssertionConditionalAndExpression.java */

package jass.parser;

public class JassAssertionConditionalAndExpression extends SimpleNode {
  public JassAssertionConditionalAndExpression(int id) {
    super(id);
  }

  public JassAssertionConditionalAndExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
