/* Generated By:JJTree: Do not edit this line. JassAssertionExclusiveOrExpression.java */

package jass.parser;

public class JassAssertionExclusiveOrExpression extends SimpleNode {
  public JassAssertionExclusiveOrExpression(int id) {
    super(id);
  }

  public JassAssertionExclusiveOrExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
