/* Generated By:JJTree: Do not edit this line. JassConditionalAndExpression.java */

package jass.parser;

public class JassConditionalAndExpression extends SimpleNode {
  public JassConditionalAndExpression(int id) {
    super(id);
  }

  public JassConditionalAndExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
