/* Generated By:JJTree: Do not edit this line. JassMethodDeclarator.java */

package jass.parser;

public class JassMethodDeclarator extends SimpleNode {
  public JassMethodDeclarator(int id) {
    super(id);
  }

  public JassMethodDeclarator(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
