/* Generated By:JJTree: Do not edit this line. JassArgumentList.java */

package jass.parser;

public class JassArgumentList extends SimpleNode {
  public JassArgumentList(int id) {
    super(id);
  }

  public JassArgumentList(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
