/* Generated By:JJTree: Do not edit this line. JassArrayDimsAndInits.java */

package jass.parser;

public class JassArrayDimsAndInits extends SimpleNode {
  public JassArrayDimsAndInits(int id) {
    super(id);
  }

  public JassArrayDimsAndInits(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
