/* Generated By:JJTree: Do not edit this line. JassAssertStatement.java */

package jass.parser;

public class JassAssertStatement extends SimpleNode {
  public JassAssertStatement(int id) {
    super(id);
  }

  public JassAssertStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
