/* Generated By:JJTree: Do not edit this line. JassTypeDeclaration.java */

package jass.parser;

public class JassTypeDeclaration extends SimpleNode {
  public JassTypeDeclaration(int id) {
    super(id);
  }

  public JassTypeDeclaration(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
