/* Generated By:JJTree: Do not edit this line. JassShiftExpression.java */

package jass.parser;

public class JassShiftExpression extends SimpleNode {
  public JassShiftExpression(int id) {
    super(id);
  }

  public JassShiftExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
