/* Generated By:JJTree: Do not edit this line. JassAndExpression.java */

package jass.parser;

public class JassAndExpression extends SimpleNode {
  public JassAndExpression(int id) {
    super(id);
  }

  public JassAndExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
