/* Generated By:JJTree: Do not edit this line. JassCheckClause.java */

package jass.parser;

public class JassCheckClause extends SimpleNode {
  public JassCheckClause(int id) {
    super(id);
  }

  public JassCheckClause(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
