/* Generated By:JJTree: Do not edit this line. JassAssertionCastLookahead.java */

package jass.parser;

public class JassAssertionCastLookahead extends SimpleNode {
  public JassAssertionCastLookahead(int id) {
    super(id);
  }

  public JassAssertionCastLookahead(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
