/* Generated By:JJTree: Do not edit this line. JassNameList.java */

package jass.parser;

public class JassNameList extends SimpleNode {
  public JassNameList(int id) {
    super(id);
  }

  public JassNameList(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
