/* Generated By:JJTree: Do not edit this line. JassLabeledStatement.java */

package jass.parser;

public class JassLabeledStatement extends SimpleNode {
  public JassLabeledStatement(int id) {
    super(id);
  }

  public JassLabeledStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
