/* Generated By:JJTree: Do not edit this line. JassCommunication.java */

package jass.parser;

public class JassCommunication extends SimpleNode {
  public JassCommunication(int id) {
    super(id);
  }

  public JassCommunication(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
