/* Generated By:JJTree: Do not edit this line. JassPrimitiveType.java */

package jass.parser;

public class JassPrimitiveType extends SimpleNode {
  public JassPrimitiveType(int id) {
    super(id);
  }

  public JassPrimitiveType(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
