/* Generated By:JJTree: Do not edit this line. JassAssertionAndExpression.java */

package jass.parser;

public class JassAssertionAndExpression extends SimpleNode {
  public JassAssertionAndExpression(int id) {
    super(id);
  }

  public JassAssertionAndExpression(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
