/* Generated By:JJTree: Do not edit this line. JassEmptyStatement.java */

package jass.parser;

public class JassEmptyStatement extends SimpleNode {
  public JassEmptyStatement(int id) {
    super(id);
  }

  public JassEmptyStatement(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
