/* Generated By:JJTree: Do not edit this line. JassBooleanAssertion.java */

package jass.parser;

public class JassBooleanAssertion extends SimpleNode {
  public JassBooleanAssertion(int id) {
    super(id);
  }

  public JassBooleanAssertion(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
