/* Generated By:JJTree: Do not edit this line. JassFormalParameters.java */

package jass.parser;

public class JassFormalParameters extends SimpleNode {
  public JassFormalParameters(int id) {
    super(id);
  }

  public JassFormalParameters(JassParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JassParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
